Repository swiftlang/swift-testing, pull requests merged in 2023-10, with the labels that each got.

#47 Silence warnings on the latest toolchain.
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug

#52 Add a protocol defining custom descriptions for types during expectation failure.
  Sources/Testing/Events/Event.Recorder.swift
  Sources/Testing/SourceAttribution/CustomTestStringConvertible.swift
  Sources/Testing/SourceAttribution/SourceCode.swift
  Sources/Testing/Support/Additions/TypeAdditions.swift
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/ParameterizedTesting.md
  Sources/TestingInternals/include/Stubs.h
  Tests/TestingTests/IssueTests.swift
Labels: enhancement

#53 Convert `StaticString`s that refer to a #filePath to `String`s so that they are `Codable`
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Issues/KnownIssue.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/SourceAttribution/SourceLocation.swift
  Sources/Testing/Traits/ConditionTrait.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/SourceLocationTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement

#57 Check availability before calling `_mangledTypeName(_:)`.
  Package.swift
  Sources/Testing/SourceAttribution/CustomTestStringConvertible.swift
  Sources/Testing/Support/Additions/TypeAdditions.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug

#54 Switch from unsafeFlags to enableExperimentalFeature to enable strict concurrency checking
  Package.swift
Labels: enhancement

#60 Fix the 256-color terminal check so it doesn't require `_StringProcessing`.
  Package.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
Labels: bug

#59 Add `borrowing` to more places that pass `Event` and `Event.Context`.
  Sources/Testing/Events/Event.Recorder.swift
  Sources/Testing/Events/Event.swift
Labels: enhancement

#68 Make `SkipInfo`, `SourceLocation`, `SourceContext`, `Test.ID`, and `Comment` conform to `Codable`
  Sources/Testing/Running/SkipInfo.swift
  Sources/Testing/SourceAttribution/SourceContext.swift
  Sources/Testing/SourceAttribution/SourceLocation.swift
  Sources/Testing/Test.ID.swift
  Sources/Testing/Traits/Comment.swift
Labels: enhancement

#48 Generalize the selectedTests facility to be closure-based, to allow filtering tests via other criteria than ID
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/Runner.Plan.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement

#8 Add CI icons to the readme
  README.md
Labels: documentation

#76 Modify Getting Started to recommend the 5.10 toolchain temporarily.
  CONTRIBUTING.md
  Sources/Testing/Testing.docc/TemporaryGettingStarted.md
Labels: documentation

#67 Make `Test.Clock.Instant` conform to `Codable`
  Sources/Testing/Events/Clock.swift
  Tests/TestingTests/ClockTests.swift
Labels: enhancement

#82 Create a `Event.[Kind.]Snapshot` type that conforms to `Codable`
  Sources/Testing/Events/Event.swift
  Sources/Testing/Expectations/Expectation.swift
  Sources/Testing/Issues/Issue.swift
  Tests/TestingTests/EventTests.swift
Labels: enhancement

#83 Generalize time types.
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Events/TimeValue.swift
  Sources/Testing/Issues/Issue.swift
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: enhancement

#81 Add a "main" entry point function for use by SPM.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
Labels: enhancement

#85 Allow converting from TimeValue to timespec
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Events/TimeValue.swift
Labels: bug, enhancement

#84 Update description of nested types and @Suite trait in vision doc
  Documentation/Vision.md
Labels: documentation

#63 Support setting a debugger breakpoint to pause when a test fails
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Running/Configuration.swift
Labels: enhancement

#87 Adopt SE-0409 (Access Level-on-Imports)
  Package.swift
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Events/TimeValue.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/Locked.swift
  Sources/Testing/Support/Versions.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/DumpTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
Labels: enhancement

#88 Warn when using `XCTestScaffold` when SwiftPM supports swift-testing.
  Sources/Testing/Events/Event.Recorder.swift
  Sources/Testing/Running/XCTestScaffold.swift
Labels: enhancement, swiftpm
