Repository swiftlang/swift-testing, pull requests merged in 2023-11, with the labels that each got.

#92 Limit usage of SE-0409 (Access Level-on-Import) to only the Testing module
  Package.swift
Labels: bug

#93 Remove `setenv()` interface and `Configuration`'s environment variables.
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Support/Environment.swift
  Tests/TestingTests/ConfigurationTests.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: swiftpm

#94 Add documentation for `.timeLimit(_:)` and reorganize trait documentation.
  Sources/Testing/Testing.docc/AddingComments.md
  Sources/Testing/Testing.docc/AddingTags.md
  Sources/Testing/Testing.docc/AssociatingBugs.md
  Sources/Testing/Testing.docc/EnablingAndDisabling.md
  Sources/Testing/Testing.docc/LimitingExecutionTime.md
  Sources/Testing/Testing.docc/Traits.md
Labels: documentation

#89 Add support for `swift test` options.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/Test.ID.swift
  Tests/TestingMacrosTests/TestSupport/Scaffolding.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/TestSupport/Scaffolding.swift
Labels: swiftpm

#61 Rethink tag colors as secondary package data.
  Sources/Testing/Events/Event.Recorder.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Testing.docc/AddingTags.md
  Sources/Testing/Traits/Tag.Color+Loading.swift
  Sources/Testing/Traits/Tag.Color.swift
  Sources/Testing/Traits/Tag.List.swift
  Sources/Testing/Traits/Tag.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement

#100 Add `includeHiddenTests` parameter to `setTestFilter(toMatch:)` APIs.
  Sources/Testing/Running/Configuration.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement

#104 Lower the 'TestCases' protocol to internal
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Test.Case.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement

#105 Remove the 'Test.Case.index' property
  Sources/Testing/Test.Case.Generator.swift
  Sources/Testing/Test.Case.swift
  Tests/TestingTests/Test.CaseTests.swift
Labels: bug

#107 Derive `Test.isParameterized` from `Test.parameters`
  Sources/Testing/Test.Case.Generator.swift
  Sources/Testing/Test.Case.swift
  Sources/Testing/Test.swift
Labels: enhancement

#109 Add an `index` property to `Test.ParameterInfo`
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.Case.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/Test.CaseTests.swift
Labels: enhancement

#113 build: ignore `TestingMacrosTest` on Windows
  Package.swift
Labels: bug

#114 Support: fix `Environment.variable(named:)` on Windows
  Sources/Testing/Support/Environment.swift
Labels: bug

#108 Implement `swift test --xunit-output`.
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
  Sources/Testing/Events/Recorder/EventRecorder.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Support/CError.swift
  Sources/Testing/Traits/Tag.Color+Loading.swift
  Sources/TestingInternals/include/Includes.h
  Sources/TestingInternals/include/Stubs.h
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/Support/CErrorTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement

#112 Represent each parameterized test function argument as a separate element in `Test.Case.arguments`
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.Case.Generator.swift
  Sources/Testing/Test.Case.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
  Tests/TestingTests/Test.CaseTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement

#116 Remove `Test.ID.Selection.testIDs` Set property
  Sources/Testing/Test.ID.Selection.swift
  Tests/TestingTests/Test.ID.SelectionTests.swift
Labels: enhancement

#115 Simplify how we filter out hidden tests.
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Tests/TestingTests/RunnerTests.swift
Labels: enhancement

#119 Remove deprecated `Event.Kind.testBypassed` enum case
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
Labels: enhancement

#121 Avoid runtime casts to parameterized protocol types, which require newer OS versions
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.Case.Generator.swift
  Sources/Testing/Test.Case.swift
  Sources/Testing/Test.swift
Labels: bug

#122 Remove synthesized `@available(*, unavailable)` attributes from test types.
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
Labels: bug

#124 Remove the `_TestCases` and `Cases` types.
  Sources/Testing/Test.Case.Generator.swift
  Sources/Testing/Test.swift
Labels: enhancement

#125 Work around a compiler regression on main.
  Tests/TestingTests/EventRecorderTests.swift
Labels: bug

#129 Tweaks to some feature conditionals.
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Traits/Tag.Color+Loading.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: bug

#131 (Tests only) Conditionalize imports of Foundation and always import TestingInternals as private.
  Package.swift
  Tests/TestingTests/BacktraceTests.swift
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/DumpTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Support/CErrorTests.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug

#133 Do not evaluate unavailable test function parameters.
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.Case.Generator.swift
  Sources/Testing/Test.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: bug

#130 Update Getting Started docs to use Swift main branch features
  CONTRIBUTING.md
  Sources/Testing/Testing.docc/TemporaryGettingStarted.md
Labels: documentation, swiftpm-integration

#136 Fix access levels of import statements to ensure compatbility with latest 'main' snapshot toolchains
  Package.swift
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/WithAttributesSyntaxAdditions.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/AvailabilityGuards.swift
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/Support/SourceLocationGeneration.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingMacrosTests/UniqueIdentifierTests.swift
Labels: bug

#137 Move test discovery code out of Test+Macros.swift.
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Test+Macro.swift
  Sources/TestingInternals/Discovery.cpp
  Sources/TestingInternals/include/Defines.h
  Sources/TestingInternals/include/Discovery.h
Labels: enhancement
