Repository swiftlang/swift-testing, pull requests merged in 2023-12, with the labels that each got.

#147 Introduce snapshot types for Test, Test.Case, and related types
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/Test.SnapshotTests.swift
Labels: enhancement

#143 Remove the old SPI-annotated SwiftPM entry point.
  Sources/Testing/Running/EntryPoint.swift
Labels: swiftpm-integration

#146 Avoid constructing a `Test` for an unavailable parameterized test function.
  Sources/Testing/Parameterization/Test.Case.Generator.swift
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/AvailabilityGuards.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: bug, darwin

#150 Remove unnecessary 'await' in calls to Test.testCases
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/Runner.Plan.SnapshotTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
Labels: enhancement

#151 Fix markup for `__invokeXCTestCaseMethod()`.
  Sources/Testing/Test+Macro.swift
Labels: documentation

#152 Fix a missing newline when emitting a warning diagnostic to the console.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
Labels: bug, swiftpm-integration

#163 Report an error when attempting to use --filter or --skip in unsupported environments
  Sources/Testing/Running/EntryPoint.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug, swiftpm-integration

#164 Expose isParameterized and isSuite on Test.Snapshot, and Test.Case.Argument.ID.init, as SPI
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/Test.SnapshotTests.swift
Labels: enhancement, tools integration
