Repository swiftlang/swift-testing, pull requests merged in 2024-05, with the labels that each got.

#388 Refactor type enumeration loop.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Test+Discovery.swift
  Sources/TestingInternals/Discovery.cpp
  Sources/TestingInternals/include/Discovery.h
Labels: enhancement

#386 Fix some bugs around `SWT_NO_*` conditionals.
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingTests/_Testing_Foundation/FoundationTests.swift
Labels: enhancement, swiftpm-integration, tools integration

#392 During test discovery, ignore Swift types in the Darwin/dyld shared cache.
  Sources/TestingInternals/Discovery.cpp
Labels: performance

#395 Clarify what it means for a symbol to be both `@_spi(Experimental)` _and_ `@_spi(ForToolsIntegrationOnly)`.
  Documentation/SPI.md
Labels: bug, documentation, tools integration

#394 Remove `Bug.Relationship`.
  Sources/Testing/Testing.docc/AssociatingBugs.md
  Sources/Testing/Testing.docc/EnablingAndDisabling.md
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Testing.docc/Traits/Trait.md
  Sources/Testing/Traits/Bug.swift
  Sources/Testing/Traits/Comment.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
  Tests/TestingTests/Traits/BugTests.swift
Labels: enhancement, tools integration, public-api

#399 Lower predefined color tags to experimental SPI.
  Sources/Testing/Testing.docc/AddingTags.md
  Sources/Testing/Traits/Tags/Tag+Predefined.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: public-api

#391 Only accept minute-granularity test time limit durations
  Sources/Testing/Traits/TimeLimitTrait.swift
  Tests/TestingTests/Test.SnapshotTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: documentation, enhancement, public-api

#358 Make Configuration.TestFilter a pure-data type
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/Running/Configuration.TestFilter.swift
  Sources/Testing/Running/Runner.Plan.swift
Labels: enhancement, tools integration

#404 Rename `TestingInternals` to `_TestingInternals`.
  Package.swift
  Package@swift-6.0.swift
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Events/TimeValue.swift
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Sources/Testing/Support/CError.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/Locked.swift
  Sources/Testing/Support/Versions.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/GetSymbol.cpp
  Sources/_TestingInternals/WillThrow.cpp
  Sources/_TestingInternals/include/Defines.h
  Sources/_TestingInternals/include/Discovery.h
  Sources/_TestingInternals/include/GetSymbol.h
  Sources/_TestingInternals/include/Includes.h
  Sources/_TestingInternals/include/Stubs.h
  Sources/_TestingInternals/include/TestSupport.h
  Sources/_TestingInternals/include/WillThrow.h
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/DumpTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Support/CErrorTests.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
  Tests/TestingTests/TypeInfoTests.swift
  Tests/TestingTests/VariadicGenericTests.swift
Labels: bug, workaround

#403 On Darwin, lock access to the `environ` block.
  Sources/Testing/Support/Environment.swift
Labels: bug, concurrency, darwin

#402 Add an experimental CLI argument for passing a configuration value as JSON.
  Sources/Testing/EntryPoints/EntryPoint.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, tools integration

#406 Remove a few unintended Foundation dependencies from our unit tests.
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
Labels: bug

#409 Work around test discovery crash when running on older OS versions due to unguarded use of .timeLimit
  Tests/TestingTests/Test.SnapshotTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: bug

#410 Avoid Regex API availability check when no filter or skip flags have been passed
  Sources/Testing/EntryPoints/EntryPoint.swift
Labels: bug

#383 Define and implement a strawman stable JSON schema for output.
  Documentation/ABI/JSON.md
  Sources/Testing/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/EntryPoints/ABIv0/ABIv0.Record+Streaming.swift
  Sources/Testing/EntryPoints/ABIv0/ABIv0.Record.swift
  Sources/Testing/EntryPoints/ABIv0/ABIv0.swift
  Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift
  Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedInstant.swift
  Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedIssue.swift
  Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift
  Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedTest.swift
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/TimeValue.swift
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Support/JSON.swift
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, tools integration, public-api

#417 Work around rdar://128091794.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
Labels: bug, workaround, swift-6

#413 Enable 'InferSendableFromCaptures' upcoming feature and resolve new build failures
  Package.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement, workaround, swift-6

#415 Silence warnings about `String.init(validatingUTF8:)` on Swift 6.
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Sources/Testing/Support/Additions/StringAdditions.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/Versions.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
Labels: bug, swift-6

#418 Add Swift 6 post-merge jobs to the readme.
  README.md
Labels: documentation, enhancement, swift-6

#420 Remove string literal tags.
  Sources/Testing/Testing.docc/AddingTags.md
  Sources/Testing/Testing.docc/DefiningTests.md
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/Testing/Testing.docc/Traits/Trait.md
  Sources/Testing/Traits/Tags/Tag.List.swift
  Sources/Testing/Traits/Tags/Tag.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/Traits/ParallelizationTraitTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: tools integration, public-api

#421 Add support for `swift test --quiet`.
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug, swiftpm-integration

#422 Always set the XCTest bundle path on Darwin when running exit tests.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/_TestingInternals/include/Includes.h
Labels: bug, tools integration, darwin

#423 Don't use `memcpy()` in a unit test.
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: bug

#387 [cmake] Build swift-testing with CMake.
  .gitignore
  CMakeLists.txt
  Documentation/CMake.md
  Sources/CMakeLists.txt
  Sources/Testing/CMakeLists.txt
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Events/TimeValue.swift
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Sources/Testing/Support/Additions/StringAdditions.swift
  Sources/Testing/Support/CError.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/Locked.swift
  Sources/Testing/Support/Versions.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/TestingMacros/CMakeLists.txt
  Sources/_TestingInternals/CMakeLists.txt
  Sources/_TestingInternals/include/module.modulemap
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/DumpTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Support/CErrorTests.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
  Tests/TestingTests/TypeInfoTests.swift
  Tests/TestingTests/VariadicGenericTests.swift
  cmake/modules/LibraryVersion.cmake
  cmake/modules/shared/AvailabilityDefinitions.cmake
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, tools integration

#426 Revert "Explicitly add visionOS availability to tests that check availability. (#424)"
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: bug, public-api

#427 Exclude CMakeLists.txt from package targets.
  Package.swift
  Package@swift-6.0.swift
Labels: bug, tools integration

#430 Fix a sendability warning in a test fixture.
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug, concurrency, swift-6

#425 Add discussion about parallelization/concurrency and tools integration to vision document draft
  Documentation/Vision.md
Labels: documentation

#431 Add an umbrella import to the `_TestingInternals` module map file.
  Sources/_TestingInternals/include/module.modulemap
Labels: bug, tools integration

#408 Behavior validation docs
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/testing-asynchronous-code.md
  Sources/Testing/Testing.docc/testing-for-errors-in-swift-code.md
Labels: documentation, enhancement

#433 Remove references to Radar from `.bug()` documentation.
  Sources/Testing/Testing.docc/BugIdentifiers.md
Labels: bug, documentation

#435 Fix two DocC symbol references to `#expect(throws:...)`
  Sources/Testing/Testing.docc/testing-for-errors-in-swift-code.md
Labels: bug, documentation

#442 Remove `Sendable` constraint on the type of `Test.testCases`.
  Sources/Testing/Test.swift
Labels: bug, concurrency, workaround, swift-6

#447 Stop proactively inserting redundant `@frozen` annotations in various macro expansions.
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
Labels: bug, swift-6
