Repository swiftlang/swift-testing, pull requests merged in 2024-09, with the labels that each got.

#656 [android] fix 32 bit android build
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/GetSymbol.swift
Labels: bug, android

#647 Optimizations to `Backtrace.current()`.
  Sources/Testing/SourceAttribution/Backtrace.swift
Labels: enhancement, tools integration, performance, swift-6.1

#657 [6.0] Reduce overhead of `.expectationChecked` event handling in `#expect()`.
  Package.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug, performance, swift-6.0.x

#659 [6.0] Reduce overhead of `.expectationChecked` event handling in `#expect()` (take 2)
  Package.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Tests/TestingTests/MiscellaneousTests.swift
  cmake/modules/shared/AvailabilityDefinitions.cmake
Labels: bug, performance, swift-6.0.x

#660 Do not include sysctl.h on Linux.
  Sources/_TestingInternals/include/Includes.h
Labels: bug, linux, build

#642 Add support for capturing backtraces from typed throws.
  Package.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/_TestingInternals/WillThrow.cpp
  Sources/_TestingInternals/include/WillThrow.h
  Tests/TestingTests/BacktraceTests.swift
  cmake/modules/shared/AvailabilityDefinitions.cmake
Labels: enhancement, swift-6.1

#655 Optimize `failureBreakpoint()`.
  Sources/Testing/Issues/Issue+Recording.swift
Labels: tools integration, performance, swift-6.1

#600 Add an EditorConfig file
  .editorconfig
Labels: enhancement, swift-6.1

#661 Remove `#expect(throws: Never.self)` and `#require(throws: Never.self)` as distinct overloads.
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Testing.docc/Expectations.md
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
Labels: documentation, enhancement, public-api, swift-6.1

#662 Replace rethrows with typed throws in Graph
  Sources/Testing/Support/Graph.swift
Labels: enhancement, embedded-swift, swift-6.1

#664 Work around compiler regression causing CI failure.
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug, darwin, workaround

#663 Work around swiftinterface generation bug on Windows.
  Sources/Testing/Issues/Issue+Recording.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug, windows, workaround, build, swift-6.1

#666 Don't use `Synchronization.Atomic` for `deliverExpectationCheckedEvents`.
  Package.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Sources/Testing/Support/Locked.swift
  cmake/modules/shared/AvailabilityDefinitions.cmake
Labels: bug, darwin, performance, swift-6.1

#669 [6.0] Work around compiler regression causing CI failure.
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug, darwin, workaround, swift-6.0.x

#667 [6.0] Don't use `Synchronization.Atomic` for `deliverExpectationCheckedEvents`.
  Package.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Sources/Testing/Support/Locked.swift
  cmake/modules/shared/AvailabilityDefinitions.cmake
Labels: bug, darwin, performance, swift-6.0.x

#670 Exit tests shouldn't emit crash logs.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/_TestingInternals/include/Includes.h
  Sources/_TestingInternals/include/Stubs.h
Labels: enhancement, windows, linux, darwin, performance, swift-6.1, exit-tests

#651 CMake: Install `_TestingInternals` in static library builds
  CMakeLists.txt
  Sources/Testing/CMakeLists.txt
  Sources/_TestingInternals/CMakeLists.txt
  cmake/modules/SwiftModuleInstallation.cmake
Labels: wasi/wasm, build, swift-6.1

#672 Fix a typo in a call of install path getter function name
  Sources/_TestingInternals/CMakeLists.txt
  Sources/_TestingInternals/include/Includes.h
Labels: bug, wasi/wasm, build, swift-6.1, exit-tests

#673 Ask Foundation to capture `NSError`/`CFError` backtraces for us.
  Sources/Testing/SourceAttribution/Backtrace.swift
  Tests/TestingTests/BacktraceTests.swift
Labels: enhancement, tools integration, darwin, swift-6.1

#652 Expose the target triple as a separate string from the testing library version.
  Package.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Support/Versions.swift
  Sources/_TestingInternals/CMakeLists.txt
  Sources/_TestingInternals/Versions.cpp
  Sources/_TestingInternals/include/Includes.h
  Sources/_TestingInternals/include/Stubs.h
  Sources/_TestingInternals/include/Versions.h
  cmake/modules/LibraryVersion.cmake
  cmake/modules/TargetTriple.cmake
Labels: enhancement, build, swift-6.1

#679 Revert "Replace rethrows with typed throws in Graph"
  Sources/Testing/Support/Graph.swift
Labels: bug, workaround, build

#680 Silence a concurrency warning on Linux/Windows building an actor-isolated test.
  Tests/TestingTests/KnownIssueTests.swift
Labels: bug, concurrency

#678 Update the reported library version for 6.0.1.
  cmake/modules/LibraryVersion.cmake
Labels: bug, build

#681 [android] fix the build
  Sources/_TestingInternals/include/Includes.h
Labels: bug, android

#677 Add the current configuration to `Event.Context`.
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Running/Configuration+EventHandling.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Sources/Testing/Running/Runner.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, tools integration, performance

#676 Optionally symbolicate backtraces.
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedBacktrace.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedEvent.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedIssue.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/SourceAttribution/Backtrace+Symbolication.swift
  Sources/_TestingInternals/include/Demangle.h
  Sources/_TestingInternals/include/Discovery.h
  Sources/_TestingInternals/include/Includes.h
  Tests/TestingTests/BacktraceTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, tools integration, windows, darwin

#685 Add platform-specific branches for FreeBSD.
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/SourceAttribution/Backtrace+Symbolication.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/GetSymbol.swift
  Sources/Testing/Support/Locked.swift
  Sources/Testing/Support/Versions.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Stubs.h
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: enhancement, help wanted, freebsd

#688 Require explicit backtrace and source location when creating and recording issues
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Issues/KnownIssue.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Running/SkipInfo.swift
  Sources/Testing/SourceAttribution/SourceContext.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Traits/ConditionTrait.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/SkipInfoTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement, issue-handling

#689 Remove the `Confirmation.ExpectedCount` marker protocol.
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/Issue.swift
  Tests/TestingTests/ConfirmationTests.swift
Labels: enhancement, tools integration, public-api, issue-handling

#690 Switch to official 600.0.0 tag for swift-syntax
  Package.swift
  Sources/TestingMacros/CMakeLists.txt
Labels: build

#695 Move `spawnAndWait(forExecutableAtPath:)` to a separate file.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
Labels: self-reviewed, exit-tests

#692 Un-revert "Replace rethrows with typed throws in Graph"
  Sources/Testing/Support/Graph.swift
Labels: enhancement, embedded-swift

#694 Add a `Pipe` type.
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: enhancement, exit-tests

#699 Disable pipes code on WASI.
  Package.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/Support/FileHandleTests.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: bug, wasi/wasm

#700 CMake: Use `CMAKE_SYSTEM_NAME STREQUAL "WASI"` instead of `WASI`
  cmake/modules/shared/CompilerSettings.cmake
Labels: bug, wasi/wasm, build

#703 Support: unwrap storage for parameter to `pipe`
  Sources/Testing/Support/FileHandle.swift
Labels: bug, android

#701 Hoist JSON Lines logic from EntryPoint.swift.
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/ABIv0.Record+Streaming.swift
  Sources/Testing/Support/Additions/NumericAdditions.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, tools integration

#704 Add manpage links for FreeBSD headers mentioned in documentation.
  Sources/Testing/ExitTests/ExitCondition.swift
Labels: documentation, self-reviewed, exit-tests, freebsd

#707 Preserve `verbosity` argument in `HumanReadableOutputRecorder.record()`.
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/ABIv0.Record+Streaming.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
Labels: bug, tools integration

#708 [6.0.1] Switch to official 600.0.0 tag for swift-syntax
  Package.swift
  Sources/TestingMacros/CMakeLists.txt
Labels: enhancement, build

#706 Remove TemporaryGettingStarted.md.
  CONTRIBUTING.md
  Documentation/README.md
  Documentation/Releases.md
  Documentation/WASI.md
  README.md
  Sources/Testing/Testing.docc/DefiningTests.md
  Sources/Testing/Testing.docc/Documentation.md
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
  Sources/Testing/Testing.docc/TemporaryGettingStarted.md
Labels: documentation, enhancement

#712 Make the `ExitTest` type move-only.
  Sources/Testing/ExitTests/ExitTest.swift
Labels: enhancement, tools integration, exit-tests

#711 Add a document about porting to new platforms.
  Documentation/Porting.md
  Documentation/README.md
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Events/TimeValue.swift
Labels: documentation, enhancement

#693 [CMake] Explicitly link Testing to Foundation
  CMakeLists.txt
  Sources/Testing/CMakeLists.txt
Labels: bug, build

#697 Record issues generated within exit tests.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/TestingMacros/ConditionMacro.swift
  Sources/_TestingInternals/CMakeLists.txt
  Sources/_TestingInternals/Stubs.cpp
  Sources/_TestingInternals/include/Stubs.h
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: enhancement, exit-tests, issue-handling

#719 Update version to 6.0.2.
  cmake/modules/LibraryVersion.cmake
Labels: build

#720 Update version to 6.0.1.
  cmake/modules/LibraryVersion.cmake
Labels: build

#721 [6.0] Switch to official 600.0.0 tag for swift-syntax (#708)
  Package.swift
  Sources/TestingMacros/CMakeLists.txt
Labels: enhancement, build

#722 Avoid accidental use of `#_sourceLocation` in the library target.
  Sources/Testing/ExitTests/ExitTest.swift
Labels: bug, build

#724 Avoid truncating the path to the test executable on Windows.
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
Labels: bug, windows, freebsd

#709 [6.0] Explicitly link to `Foundation` in CMake builds
  CMakeLists.txt
  Sources/Testing/CMakeLists.txt
Labels: bug, windows, build

#726 Remove extraneous @escaping and @Sendable attributes from CustomExecutionTrait.execute(...) SPI
  Sources/Testing/Traits/Trait.swift
  Tests/TestingTests/Traits/CustomExecutionTraitTests.swift
Labels: enhancement

#728 Walk PE files' sections instead of using `swift_enumerateAllMetadataSections()`.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Test+Discovery.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Discovery.h
Labels: enhancement, windows, performance

#713 [6.0.2][CMake] Explicitly link Testing to Foundation
  CMakeLists.txt
  Sources/Testing/CMakeLists.txt
Labels: bug, windows, build

#731 Fix the 32-bit Windows build
  Sources/_TestingInternals/Discovery.cpp
Labels: bug, windows

#730 Don't use `swift_enumerateAllMetadataSections()` on WASI.
  Sources/_TestingInternals/Discovery.cpp
Labels: enhancement, performance, wasi/wasm

#734 Only call `getsectiondata()` once per image.
  Sources/_TestingInternals/Discovery.cpp
Labels: enhancement, darwin, performance

#718 Distinguish when an error is part of a recorded issue in an exit test.
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedBacktrace.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedError.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedIssue.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/ExitTest.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: enhancement, tools integration, exit-tests, issue-handling

#732 Reset default signal handlers on child processes before spawning them.
  Sources/Testing/ExitTests/SpawnProcess.swift
Labels: bug, linux, darwin, exit-tests, freebsd

#737 Set `RLIMIT_CORE=1` instead of `=0` on Linux.
  Sources/Testing/ExitTests/ExitTest.swift
Labels: bug, linux, performance, exit-tests

#741 Do not emit a `time=` attribute in JUnit output for skipped tests.
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: bug, swiftpm-integration, tools integration

#736 Inherit isolation in `#expect(exitsWith:)`.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: bug, concurrency, exit-tests

#739 Fix macro expansion failure for a non-copyable suite type with a `test` method.
  Sources/Testing/Test+Macro.swift
  Tests/TestingTests/NonCopyableSuiteTests.swift
Labels: bug
