Repository swiftlang/swift-testing, pull requests merged in 2024-02, with the labels that each got.

#199 Distinguish string literals in `Expression`.
  Sources/Testing/SourceAttribution/Expression+Macro.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Sources/TestingMacros/Support/SourceCodeCapturing.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, swiftpm-integration, tools integration

#203 Adjust uses of `fopen()` and `strerror()` on Windows.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Support/CError.swift
  Tests/TestingTests/Support/CErrorTests.swift
Labels: bug, windows

#204 Do not use `String.init(validatingUTF8: [CChar])`.
  Sources/Testing/Support/Versions.swift
Labels: bug, swift-6

#201 Add a document describing how to tag a release.
  Documentation/Releases.md
Labels: documentation

#206 Add main-branch build icons to README.
  README.md
Labels: documentation, linux, darwin

#207 Fix miscompile when using `is` and `as?` with `any P` in an expectation.
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug

#205 Add support for `swift test --verbose`.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: enhancement, swiftpm-integration

#213 Reduce the package manifest's tools version requirement to 5.9.
  Package.swift
Labels: bug, tools integration, workaround, public-api

#214 Change `var` to `let` to suppress a warning.
  Sources/Testing/SourceAttribution/Expression.swift
Labels: bug

#215 Work around an issue in the toolchain calling `Result.get()`.
  Sources/Testing/Support/Additions/ResultAdditions.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug, workaround

#216 Expand on `Test.current` and why it is optional.
  Sources/Testing/Running/Runner.RuntimeState.swift
Labels: documentation, concurrency

#218 Support re-running parameterized tests with RawRepresentable arguments automatically
  Sources/Testing/Parameterization/CustomTestArgumentEncodable.swift
  Sources/Testing/Testing.docc/ParameterizedTesting.md
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
Labels: documentation, enhancement

#219 Reduce the sizes of `Event.Kind`, `Issue.Kind`, and `Runner.Plan.Action`.
  Sources/Testing/Events/Event.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Running/Runner.Plan.swift
Labels: enhancement, performance

#220 Migrate file I/O code to a dedicated `FileHandle` type.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/TestingInternals/include/Includes.h
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: enhancement

#86 Add the ability for a trait to run code before and after a test
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Traits/Trait.swift
  Tests/TestingTests/Traits/CustomExecutionTraitTests.swift
Labels: enhancement, public-api

#221 Make Expression.expandedDescription(depth:includingTypeNames:includingParenthesesIfNeeded:) -> String SPI
  Sources/Testing/SourceAttribution/Expression.swift
Labels: enhancement, tools integration

#222 Add more checks for `SWT_NO_FILE_IO`.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
Labels: bug, embedded-swift

#217 Add a `.serial` trait that forces a test to run its content serially.
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/Testing/Testing.docc/Parallelization.md
  Sources/Testing/Testing.docc/ParameterizedTesting.md
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Traits/SPIAwareTrait.swift
  Sources/Testing/Traits/SerialTrait.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/Traits/SerialTraitTests.swift
Labels: enhancement, concurrency, public-api

#208 Implement a test iteration feature.
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/Runner.swift
  Tests/TestingTests/PlanIterationTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, concurrency, swiftpm-integration

#227 Fix build when `SWT_NO_ENVIRONMENT_VARIABLES` is set.
  Sources/Testing/Support/Environment.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
Labels: bug, embedded-swift

#226 Convert uses of `@unchecked Sendable` to checked `Sendable`.
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/Locked.swift
Labels: concurrency

#224 Add 'README' to Documentation directory, and remove .docc symlink
  Documentation/README.md
  Documentation/Testing.docc
Labels: documentation

#229 Represent type information for test parameters and their runtime arguments
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Sources/Testing/Test+Macro.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
  Tests/TestingTests/TypeInfoTests.swift
Labels: enhancement, tools integration

#232 Add to /Documentation a copy of the forum post describing our SPI policy.
  Documentation/README.md
  Documentation/SPI.md
Labels: documentation, tools integration

#233 Fix typo in AddingTags document
  Sources/Testing/Testing.docc/AddingTags.md
Labels: bug, documentation

#235 Ensure that type names used in extensions are correctly parsed.
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/Support/Additions/TypeAdditions.swift
  Sources/Testing/Test+Macro.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
  Tests/TestingTests/TypeInfoTests.swift
Labels: bug

#237 Fix a stray warning in a test.
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug

#238 Remove a stray `print()` in a test.
  Tests/TestingTests/PlanTests.swift
Labels: bug

#239 Avoid direct calls to `fwrite()` and `fputs()`.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: bug, windows

#223 Rethink symbolic vs. string literal tags.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Testing.docc/AddingTags.md
  Sources/Testing/Testing.docc/DefiningTests.md
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/Testing/Traits/Tag+Macro.swift
  Sources/Testing/Traits/Tag.Color.swift
  Sources/Testing/Traits/Tag.List.swift
  Sources/Testing/Traits/Tag.swift
  Sources/Testing/Traits/Trait.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/Support/TagConstraints.swift
  Sources/TestingMacros/TagMacro.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/Traits/BugTests.swift
  Tests/TestingTests/Traits/CommentTests.swift
  Tests/TestingTests/Traits/HiddenTraitTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: enhancement, swiftpm-integration, tools integration, public-api

#241 Don't use `@Tag` in the library target.
  Sources/Testing/Traits/Tag.Color.swift
Labels: bug, public-api

#236 Rename `Package@swift-5.11.swift` to `Package@swift-6.0.swift`
  Documentation/Releases.md
  Package@swift-6.0.swift
Labels: bug, swift-6

#242 `swift test --list` should write to `stdout` rather than calling `print()`.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/TestingInternals/include/Stubs.h
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: bug, swiftpm-integration
