Repository swiftlang/swift-testing, pull requests merged in 2024-12, with the labels that each got.

#825 Configure CMake to build and install the Foundation cross-import overlay
  Sources/CMakeLists.txt
  Sources/Overlays/CMakeLists.txt
  Sources/Overlays/_Testing_Foundation/CMakeLists.txt
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Testing.swiftcrossimport/Foundation.swiftoverlay
  cmake/modules/SwiftModuleInstallation.cmake
Labels: enhancement, build

#835 Document the steps for building & installing the project for macOS using CMake
  CONTRIBUTING.md
Labels: documentation, build

#838 Revert "[6.1] Remove '-dev' from package version"
  cmake/modules/LibraryVersion.cmake
Labels: bug

#839 [6.1] Remove '-dev' from package version
  cmake/modules/LibraryVersion.cmake
Labels: build

#833 Bump the Swift version to 6.2
  cmake/modules/LibraryVersion.cmake
Labels: build

#837 Don't install the binary Swift module when building for Apple platforms
  cmake/modules/SwiftModuleInstallation.cmake
Labels: enhancement, build

#826 Change archive format for directories to .zip and add iOS/etc. support.
  Sources/Overlays/_Testing_Foundation/Attachments/Attachment+URL.swift
  Tests/TestingTests/AttachmentTests.swift
Labels: enhancement, attachments/activities

#827 Add a CoreGraphics cross-import overlay with support for attaching `CGImage`s.
  Package.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/AttachableAsCGImage.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/Attachment+AttachableAsCGImage.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/CGImage+AttachableAsCGImage.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/ImageAttachmentError.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/_AttachableImageContainer.swift
  Sources/Overlays/_Testing_CoreGraphics/ReexportTesting.swift
  Tests/TestingTests/AttachmentTests.swift
Labels: enhancement, darwin, public-api, attachments/activities

#836 Fix DocC warnings and errors, including those from SPI
  Sources/Testing/Attachments/Attachment.swift
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Parameterization/Test.Case.Generator.swift
  Sources/Testing/Running/Configuration.TestFilter.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/Runner.Plan+Dumping.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Support/CartesianProduct.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Testing.docc/LimitingExecutionTime.md
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Testing.docc/Traits/Trait.md
  Sources/Testing/Traits/ConditionTrait.swift
  Sources/Testing/Traits/TimeLimitTrait.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: documentation

#849 Make `Attachment` conform to `CustomStringConvertible`.
  Sources/Testing/Attachments/Attachment.swift
  Tests/TestingTests/AttachmentTests.swift
Labels: enhancement, public-api, attachments/activities

#847 Adopt prerelease tags of swift-syntax-601.
  Package.swift
  Sources/TestingMacros/CMakeLists.txt
  Sources/TestingMacros/SuiteDeclarationMacro.swift
Labels: bug, build

#834 Simplify the logic for parsing and handling test arguments in the @Test macro
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
Labels: enhancement

#850 Fix multiline comments not rendering correctly at CLI.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
Labels: bug, tools integration, command-line experience

#852 [6.1] Fix multiline comments not rendering correctly at CLI.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
Labels: bug, tools integration, command-line experience

#851 [6.1] Adopt prerelease tags of swift-syntax-601.
  Package.swift
  Sources/TestingMacros/CMakeLists.txt
  Sources/TestingMacros/SuiteDeclarationMacro.swift
Labels: bug, build

#855 Fix `posix_spawn()` error handling.
  Sources/Testing/ExitTests/SpawnProcess.swift
Labels: bug, linux, darwin, exit-tests, freebsd

#854 Add a `preferredName(for:basedOn:)` member to `Attachable` to allow customizing filenames.
  Documentation/StyleGuide.md
  Sources/Overlays/_Testing_CoreGraphics/Attachments/Attachment+AttachableAsCGImage.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/ImageAttachmentError.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/_AttachableImageContainer.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Attachable+Encodable.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Attachable+NSSecureCoding.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Attachment+URL.swift
  Sources/Overlays/_Testing_Foundation/Attachments/EncodingFormat.swift
  Sources/Overlays/_Testing_Foundation/Attachments/_AttachableURLContainer.swift
  Sources/Overlays/_Testing_Foundation/CMakeLists.txt
  Sources/Testing/Attachments/Attachable.swift
  Sources/Testing/Attachments/Attachment.swift
  Tests/TestingTests/AttachmentTests.swift
Labels: enhancement, public-api, attachments/activities

#856 build: tweak for portability with exceptions
  Sources/_TestingInternals/CMakeLists.txt
Labels: bug, windows, build

#853 Add example for how to test any error is thrown in the error testing documentation article
  Sources/Testing/Testing.docc/testing-for-errors-in-swift-code.md
Labels: documentation, enhancement

#780 [SWT-0006] Return the thrown error from `#expect(throws:)` and `#require(throws:)`.
  Documentation/Proposals/0006-return-errors-from-expect-throws.md
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Support/Additions/ResultAdditions.swift
  Sources/Testing/Support/SystemError.swift
  Sources/Testing/Testing.docc/AvailabilityStubs/ExpectComplexThrows.md
  Sources/Testing/Testing.docc/AvailabilityStubs/RequireComplexThrows.md
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
  Sources/Testing/Testing.docc/testing-for-errors-in-swift-code.md
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, public-api, api-proposal, issue-handling

#857 [6.1] [SWT-0006] Return the thrown error from `#expect(throws:)` and `#require(throws:)`.
  Documentation/Proposals/0006-return-errors-from-expect-throws.md
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Support/Additions/ResultAdditions.swift
  Sources/Testing/Support/SystemError.swift
  Sources/Testing/Testing.docc/AvailabilityStubs/ExpectComplexThrows.md
  Sources/Testing/Testing.docc/AvailabilityStubs/RequireComplexThrows.md
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
  Sources/Testing/Testing.docc/testing-for-errors-in-swift-code.md
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, public-api, issue-handling

#858 Change default behavior of exit tests to always succeed.
  Sources/Testing/ExitTests/ExitTest.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: bug, exit-tests

#864 Remove an import of UniformTypeIdentifiers from the Foundation overlay.
  Sources/Overlays/_Testing_Foundation/Attachments/Attachment+URL.swift
Labels: bug, darwin, attachments/activities

#865 Additional FreeBSD fixes
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Support/Locked.swift
  Sources/_TestingInternals/include/Includes.h
Labels: bug, freebsd

#867 Fix more things on FreeBSD
  Package.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/CError.swift
Labels: bug, build, freebsd

#871 Fix some typos in the new FreeBSD-specific code.
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Support/Locked.swift
Labels: bug, documentation, freebsd

#870 Add `@_spi` annotations to reexport decls in cross-import overlays.
  Sources/Overlays/_Testing_CoreGraphics/ReexportTesting.swift
  Sources/Overlays/_Testing_Foundation/ReexportTesting.swift
Labels: bug, build

#872 Remove the workaround for swift-package-manager-#8111.
  Package.swift
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: windows, workaround, build

#874 Don't use `@_semantics`, use our own attribute instead.
  Sources/Testing/Test+Macro.swift
  Sources/TestingMacros/CMakeLists.txt
  Sources/TestingMacros/PragmaMacro.swift
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/PragmaMacroTests.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug
