Repository swiftlang/swift-testing, pull requests merged in 2024-10, with the labels that each got.

#744 Disable formatting for more macros.
  Sources/TestingMacros/SourceLocationMacro.swift
  Sources/TestingMacros/TagMacro.swift
Labels: bug, workaround, performance

#742 Bump the Swift version to 6.0.3
  cmake/modules/LibraryVersion.cmake
Labels: build

#747 Simplify the configuration option for synchronous test isolation.
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Test+Macro.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: enhancement, tools integration, performance

#750 Simplify the thunk names we generate for test functions.
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Tests/TestingMacrosTests/UniqueIdentifierTests.swift
Labels: enhancement, workaround

#753 Fix a test that fails to compile on 32-bit targets.
  Tests/TestingTests/IssueTests.swift
Labels: bug

#754 Work around a compiler crash trying to demangle an expression macro inside an attached macro expansion.
  Tests/TestingTests/EventTests.swift
Labels: bug, workaround

#758 Stub out symbolication on platforms without dynamic linking/loading.
  Sources/Testing/SourceAttribution/Backtrace+Symbolication.swift
  Tests/TestingTests/BacktraceTests.swift
Labels: bug, wasi/wasm

#759 Remove unintentional label from 'isolated' parameter on a thunk emitted by @Test
  Sources/TestingMacros/TestDeclarationMacro.swift
Labels: bug

#761 Combine the test discovery implementations for WASI and static Mach-O.
  Package.swift
  Sources/_TestingInternals/Discovery.cpp
Labels: darwin, wasi/wasm

#763 Update Porting.md to describe how to handle platforms that use static linkage.
  Documentation/Porting.md
Labels: documentation, enhancement, embedded-swift

#767 Fix missing newlines in error JSON propagated from an exit test.
  Sources/Testing/ExitTests/ExitTest.swift
Labels: bug, self-reviewed, exit-tests

#768 Add `.index-build` to `.gitignore`
  .gitignore
Labels: enhancement, build

#769 Split `SWT_NO_EXIT_TESTS` into `SWT_NO_EXIT_TESTS` and `SWT_NO_PROCESS_SPAWNING`.
  Package.swift
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/WaitFor.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, exit-tests, attachments/activities

#762 Add a return type for exit tests.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/ExitTest.Result.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: enhancement, tools integration, public-api, exit-tests

#772 Update documentation to explain misconfigurations of `SWT_` conditions.
  Documentation/Porting.md
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/FileHandle.swift
Labels: bug, documentation, exit-tests

#766 Handle signals on Windows in exit tests.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Support/Additions/WinSDKAdditions.swift
  Sources/_TestingInternals/include/Includes.h
  Tests/TestingTests/ExitTestTests.swift
Labels: enhancement, windows, workaround, exit-tests

#776 Avoid using `NTSTATUS` near `exit()`.
  Sources/Testing/Support/Additions/WinSDKAdditions.swift
Labels: bug, windows, exit-tests

#778 Ensure trailing trivia is trimmed from @Suite trait expressions
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug

#779 Make the result of an exit test optional with `#expect`.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.Result.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/ExitTestArtifacts.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Support/Additions/ResultAdditions.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: enhancement, public-api, exit-tests

#773 Add support for collecting `stdout` and `stderr` in an exit test.
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/ExitTestArtifacts.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Support/Additions/ResultAdditions.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: enhancement, tools integration, exit-tests, command-line experience

#781 Make `ExitTestArtifacts.observedValues` properly sendable.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
Labels: bug, concurrency, tools integration, exit-tests

#782 Fix some compiler conditional uses (`SWT_NO_*`).
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/ABIv0.Record+Streaming.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
Labels: bug, embedded-swift, build, self-reviewed

#691 [SWT-0005] Range-based confirmations
  Documentation/Proposals/0005-ranged-confirmations.md
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
  Sources/Testing/Testing.docc/testing-asynchronous-code.md
  Tests/TestingTests/ConfirmationTests.swift
  Tests/TestingTests/IssueTests.swift
Labels: enhancement, public-api, api-proposal

#784 Update documentation for new `confirmation()` overload.
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Testing.docc/AvailabilityStubs/Issues/Confirmation.md
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
  Sources/Testing/Testing.docc/testing-asynchronous-code.md
Labels: bug, documentation, enhancement

#787 Ensure the identifier of a "seen" object is only removed if the object's children were recursively reflected
  Sources/Testing/SourceAttribution/Expression.swift
  Tests/TestingTests/Expression.ValueTests.swift
Labels: bug, tools integration, issue-handling
