Repository swiftlang/swift-testing, pull requests merged in 2024-03, with the labels that each got.

#245 Fix a docs typo
  Sources/Testing/Testing.docc/AddingTags.md
Labels: bug, documentation

#244 Allow combining `TestFilter` instances with `OR`-like semantics.
  Sources/Testing/Running/Configuration.TestFilter.swift
  Tests/TestingTests/PlanTests.swift
Labels: enhancement, tools integration

#246 Replace unsafe '-define-availability' flags with experimental AvailabilityMacro feature
  Documentation/Releases.md
  Package.swift
  Package@swift-6.0.swift
Labels: documentation, enhancement

#248 Add additional warnings for unimplemented platform-specific stuff.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/TestingInternals/Discovery.cpp
  Tests/TestingTests/Support/EnvironmentTests.swift
Labels: bug, embedded-swift, wasi/wasm

#250 Polish `XCTestScaffold` and `Tag` docs.
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/Testing.docc/AddingTags.md
Labels: bug, documentation, public-api

#257 Support multiple `--filter` and `--skip` arguments.
  Sources/Testing/Running/Configuration.TestFilter.swift
  Sources/Testing/Running/EntryPoint.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug, swiftpm-integration

#259 Ensure `indirect` is applied consistently to `Event.Kind(.Snapshot)` enum cases
  Sources/Testing/Events/Event.swift
Labels: bug

#260 Lower programmatic `.comment` trait to SPI
  Sources/Testing/Testing.docc/AddingComments.md
  Sources/Testing/Traits/Comment.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/Traits/CommentTests.swift
Labels: documentation, public-api

#261 Add support for true color in Terminal output.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Running/EntryPoint.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: enhancement, windows, linux

#262 Document `#expect { ... } throws: { ... }` in XCTest migration article
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
Labels: documentation

#263 Add missing 'testCaseID' property to Event.Snapshot
  Sources/Testing/Events/Event.swift
Labels: bug, tools integration

#264 Introduce a snapshot type for Error values
  Sources/Testing/Issues/ErrorSnapshot.swift
  Sources/Testing/Issues/Issue.swift
  Tests/TestingTests/IssueTests.swift
Labels: enhancement, tools integration

#265 Move snapshot types from SPI group `ExperimentalSnapshotting` to `ForToolsIntegrationOnly`.
  Sources/Testing/Events/Event.swift
  Sources/Testing/Expectations/Expectation.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Runner.Plan.SnapshotTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
Labels: tools integration

#266 Move event recorders from SPI group `ExperimentalEventRecording` to `ForToolsIntegrationOnly`.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: tools integration

#268 Move symbols from SPI group `ExperimentalParameterizedTesting` to `ForToolsIntegrationOnly`.
  Sources/Testing/Parameterization/CustomTestArgumentEncodable.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
Labels: tools integration

#267 Move symbols from SPI group `ExperimentalSourceCodeCapturing` to `ForToolsIntegrationOnly`.
  Sources/Testing/SourceAttribution/Expression.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: tools integration

#271 Add unit tests for `UncheckedSendable`.
  Tests/TestingTests/Support/UncheckedSendableTests.swift
Labels: enhancement

#270 Move `Event` from SPI group `ExperimentalEventHandling` to `ForToolsIntegrationOnly`.
  Sources/Testing/Events/Event.swift
  Sources/Testing/Running/Configuration.swift
  Tests/TestingTests/BacktraceTests.swift
  Tests/TestingTests/ConfirmationTests.swift
  Tests/TestingTests/KnownIssueTests.swift
  Tests/TestingTests/ObjCInteropTests.swift
  Tests/TestingTests/PlanIterationTests.swift
  Tests/TestingTests/Runner.RuntimeStateTests.swift
  Tests/TestingTests/SourceLocationTests.swift
  Tests/TestingTests/Traits/CustomExecutionTraitTests.swift
  Tests/TestingTests/Traits/SerialTraitTests.swift
Labels: tools integration

#273 Move `Test.xcTestCompatibleSelector` to SPI group `ForToolsIntegrationOnly`.
  Sources/Testing/Test.swift
Labels: tools integration

#272 Move `Configuration` to SPI group `ForToolsIntegrationOnly`.
  Sources/Testing/Running/Configuration.swift
  Tests/TestingTests/KnownIssueTests.swift
  Tests/TestingTests/Runner.RuntimeStateTests.swift
  Tests/TestingTests/SourceLocationTests.swift
  Tests/TestingTests/Traits/CustomExecutionTraitTests.swift
Labels: tools integration

#274 Move `Comment.Kind` to SPI group `ForToolsIntegrationOnly`.
  Sources/Testing/Traits/Comment.swift
Labels: tools integration

#275 Move `Test.Clock` to SPI groups `Experimental` and `ForToolsIntegrationOnly`.
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Expectations/Expectation.swift
  Sources/_Testing_Foundation/Events/Clock+Date.swift
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
  Tests/TestingTests/_Testing_Foundation/FoundationTests.swift
Labels: tools integration

#276 Diagnose ambiguous uses of `#require()` with an argument of type `Bool?`.
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
Labels: enhancement, public-api

#277 Make value capture of optionals more robust.
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug

#278 Move `Runner` and contained symbols to SPI group `ForToolsIntegrationOnly`.
  Sources/Testing/Events/Event.swift
  Sources/Testing/Running/Runner.Plan+Dumping.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Running/Runner.swift
  Tests/TestingTests/BacktraceTests.swift
  Tests/TestingTests/ConfirmationTests.swift
  Tests/TestingTests/DumpTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/ObjCInteropTests.swift
  Tests/TestingTests/PlanIterationTests.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/Runner.Plan.SnapshotTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
  Tests/TestingTests/Test.ID.SelectionTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
  Tests/TestingTests/Traits/CommentTests.swift
  Tests/TestingTests/Traits/SerialTraitTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
  Tests/TestingTests/ZipTests.swift
Labels: tools integration

#251 Refactor predefined tag/color logic.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Traits/Tags/Tag+Macro.swift
  Sources/Testing/Traits/Tags/Tag+Predefined.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/Testing/Traits/Tags/Tag.Color.swift
  Sources/Testing/Traits/Tags/Tag.List.swift
  Sources/Testing/Traits/Tags/Tag.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, public-api

#249 Adopt swift-syntax 5.10.
  Package.swift
  Package@swift-6.0.swift
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
Labels: enhancement

#281 Add documentation for `_checkAmbiguousArgument(_:in:)`.
  Sources/TestingMacros/ConditionMacro.swift
Labels: bug, documentation

#282 Move remaining SPI to SPI group `ForToolsIntegrationOnly`.
  Sources/Testing/Parameterization/Test.Case.ID.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Running/SkipInfo.swift
  Sources/Testing/Test.ID.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/SkipInfoTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/Traits/CustomExecutionTraitTests.swift
Labels: tools integration

#283 Make event recorder types non-copyable.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
Labels: enhancement

#284 Make `Event.Context` non-copyable.
  Sources/Testing/Events/Event.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
Labels: enhancement

#285 Improve 16-color console output.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Traits/Tags/Tag.Color.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, tools integration

#287 Fix typo
  Documentation/README.md
Labels: bug, documentation

#289 Improve Unicode characters used for CLI output on Windows.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: enhancement, windows

#280 Add a template for new feature or API proposals
  Documentation/Proposals/0000-proposal-template.md
Labels: documentation, public-api

#290 Add a `comment` property to the `.bug()` trait.
  Sources/Testing/Testing.docc/AssociatingBugs.md
  Sources/Testing/Testing.docc/EnablingAndDisabling.md
  Sources/Testing/Traits/Bug.swift
  Sources/Testing/Traits/Comment.swift
  Tests/TestingTests/Traits/BugTests.swift
Labels: enhancement, tools integration, public-api

#288 Drop remaining 5.9 support.
  Package.swift
  Sources/Testing/Testing.docc/DefiningTests.md
  Sources/Testing/Testing.docc/TemporaryGettingStarted.md
Labels: public-api

#292 Mention the need for a dev toolchain in the package readme.
  CONTRIBUTING.md
  README.md
  Sources/Testing/Testing.docc/TemporaryGettingStarted.md
Labels: documentation

#291 Remove an unused parameter from `Runner._withErrorHandling()` and improve its documentation
  Sources/Testing/Running/Runner.swift
Labels: bug, documentation

#293 Only load tag colors from disk if color output is enabled.
  Sources/Testing/Running/EntryPoint.swift
Labels: bug, performance

#303 Use `#if compiler` instead of `#if swift` with access levels on import.
  Sources/TestingMacros/Support/Additions/DeclGroupSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/TokenSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/TriviaPieceAdditions.swift
  Sources/TestingMacros/Support/Additions/TypeSyntaxProtocolAdditions.swift
  Sources/TestingMacros/Support/Additions/VersionTupleSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/WithAttributesSyntaxAdditions.swift
  Sources/TestingMacros/Support/Argument.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/AvailabilityGuards.swift
  Sources/TestingMacros/Support/CommentParsing.swift
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/Support/SourceCodeCapturing.swift
  Sources/TestingMacros/Support/SourceLocationGeneration.swift
  Sources/TestingMacros/Support/TagConstraints.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Sources/_Testing_Foundation/ReexportTesting.swift
Labels: bug, swift-6

#302 Warn about effectful expectations.
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/Runner.Plan.SnapshotTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
Labels: bug, enhancement, public-api

#306 Revert "Make `Event.Context` non-copyable. (#284)"
  Sources/Testing/Events/Event.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
Labels: bug, concurrency

#286 Add experimental support for event streaming using JSON.
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, swiftpm-integration, tools integration

#294 Include test names in verbose output.
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: enhancement, swiftpm-integration, tools integration

#309 Do not assume `UnsafeRawBufferPointer` provides contiguous storage.
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: bug, darwin

#310 Adopt `TypeInfo` in `Test`.
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.ID.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/ObjCInteropTests.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/TypeInfoTests.swift
Labels: enhancement, tools integration, embedded-swift

#313 Fix some variable names in #310.
  Sources/Testing/Parameterization/TypeInfo.swift
Labels: bug

#311 Synthesize `Test` instances for all suite types.
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/PlanTests.swift
Labels: bug, tools integration

#316 Fix issues building when using Xcode Command Line Tools (no XCTest.)
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/Traits/TimeLimitTrait.swift
  Tests/TestingMacrosTests/TestSupport/Scaffolding.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/ObjCInteropTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/TestSupport/Scaffolding.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: bug, swiftpm-integration, darwin, swift-6

#318 Flatten call stack when using `TypeInfo`.
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/SourceAttribution/CustomTestStringConvertible.swift
  Sources/Testing/Support/Additions/TypeAdditions.swift
  Sources/Testing/Traits/Tags/Tag+Macro.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/TypeInfoTests.swift
Labels: enhancement, performance

#319 Some tweaks to the markup for `Test.ID`.
  Sources/Testing/Test.ID.swift
Labels: bug, documentation
