Repository swiftlang/swift-testing, pull requests merged in 2024-06, with the labels that each got.

#448 Ensure `@Test(arguments:)` macro expansion trims trivia from argument expressions
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug

#449 Avoid infinite recursion when snapshotting objects which may have cyclic references
  Sources/Testing/SourceAttribution/Expression.swift
  Tests/TestingTests/Expression.ValueTests.swift
Labels: bug

#451 Some minor housekeeping.
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/_TestingInternals/include/Stubs.h
Labels: bug, enhancement, tools integration

#452 Move dynamic loader abstraction up to Swift.
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/GetSymbol.swift
  Sources/Testing/Support/Versions.swift
  Sources/_TestingInternals/GetSymbol.cpp
  Sources/_TestingInternals/include/GetSymbol.h
  Sources/_TestingInternals/include/Includes.h
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: enhancement, windows, linux, darwin

#454 Throw errors from the ABI entry point instead of crashing.
  Sources/Testing/EntryPoints/ABIEntryPoint.swift
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: bug, tools integration

#455 Reduce the number of calls to `Environment.variable(named:)`.
  Sources/Testing/Support/JSON.swift
Labels: bug, tools integration, performance

#456 Fix mistakes in documentation comments for internal JSON-streaming interfaces.
  Sources/Testing/EntryPoints/ABIv0/ABIv0.Record+Streaming.swift
Labels: bug, documentation

#457 Fix CMake files referencing GetSymbol.cpp -> GetSymbol.swift.
  Sources/Testing/CMakeLists.txt
  Sources/_TestingInternals/CMakeLists.txt
Labels: bug, tools integration

#459 [cmake] Fix inconsistently imported warning.
  Sources/Testing/Support/GetSymbol.swift
Labels: bug

#458 Increase test coverage using exit tests.
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/ConfirmationTests.swift
  Tests/TestingTests/PlanIterationTests.swift
  Tests/TestingTests/SourceLocationTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: enhancement

#441 Warn about the use of `.serialized` with non-parameterized test functions
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
Labels: enhancement

#462 Delete the workaround for `CommandLine.arguments` being concurrency-unsafe.
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: workaround, swift-6

#463 Ensure default property values for `__CommandLineArguments_v0` are all `nil`.
  Sources/Testing/EntryPoints/EntryPoint.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug, swiftpm-integration, tools integration

#465 Fix Tag example in documentation.
  Sources/Testing/Testing.docc/AddingTags.md
Labels: documentation

#466 Update README and other documentation files
  CONTRIBUTING.md
  Documentation/CMake.md
  Documentation/README.md
  Documentation/Releases.md
  Documentation/SPI.md
  Documentation/Vision.md
  NOTICE.txt
  README.md
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
  Sources/Testing/Testing.docc/TemporaryGettingStarted.md
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/TestingMacros/TestingMacrosMain.swift
Labels: documentation

#470 Switch doc generation to use 6.0
  .spi.yml
Labels: tools integration, swift-6

#467 Remove remaining Swift 5.10 support.
  .spi.yml
  Package.swift
  Package@swift-6.0.swift
  README.md
  Sources/Testing/CMakeLists.txt
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/Additions/StringAdditions.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/Versions.swift
  Sources/Testing/Testing.docc/TemporaryGettingStarted.md
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/Testing/Traits/TimeLimitTrait.swift
  Sources/TestingMacros/Support/Additions/DeclGroupSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/EditorPlaceholderExprSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Sources/TestingMacros/Support/Additions/TokenSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/TriviaPieceAdditions.swift
  Sources/TestingMacros/Support/Additions/TypeSyntaxProtocolAdditions.swift
  Sources/TestingMacros/Support/Additions/VersionTupleSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/WithAttributesSyntaxAdditions.swift
  Sources/TestingMacros/Support/Argument.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/AvailabilityGuards.swift
  Sources/TestingMacros/Support/CommentParsing.swift
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/Support/SourceCodeCapturing.swift
  Sources/TestingMacros/Support/SourceLocationGeneration.swift
  Sources/TestingMacros/TagMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Sources/_Testing_Foundation/ReexportTesting.swift
  Tests/TestingMacrosTests/TagMacroTests.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Scaffolding.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/TestSupport/Scaffolding.swift
Labels: tools integration, public-api, swift-6

#477 Explicitly add visionOS availability to tests that check availability (Take 2)
  Package.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: bug

#304 Replace `#fileID`, `#filePath`, `#line`, and `#column` with a single macro.
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Issues/KnownIssue.swift
  Sources/Testing/SourceAttribution/SourceLocation+Macro.swift
  Sources/Testing/SourceAttribution/SourceLocation.swift
  Sources/Testing/Support/SystemError.swift
  Sources/Testing/Testing.docc/EnablingAndDisabling.md
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Testing.docc/Traits/Trait.md
  Sources/Testing/Testing.docc/known-issues.md
  Sources/Testing/Testing.docc/testing-asynchronous-code.md
  Sources/Testing/Testing.docc/testing-for-errors-in-swift-code.md
  Sources/Testing/Traits/ConditionTrait.swift
  Sources/TestingMacros/SourceLocationMacro.swift
  Sources/TestingMacros/Support/SourceLocationGeneration.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/SkipInfoTests.swift
  Tests/TestingTests/SourceLocationTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement, public-api, swift-6

#482 Don't emit JSON blobs for test cases if a test function isn't parameterized.
  Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift
Labels: bug, tools integration

#488 Fix miscompile with inferred base expression of member access expression.
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug

#484 Updating documentation overview and availability info
  Sources/Testing/Testing.docc/Documentation.md
  Sources/Testing/Testing.docc/Info.plist
Labels: documentation

#489 Allow `nil` comments to be passed to `#expect()` or `#require()`.
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingTests/Traits/CommentTests.swift
Labels: bug

#450 Include fix-its in the diagnostic on a parameterized test when `@Test` is missing `arguments:`
  Sources/TestingMacros/Support/Additions/EditorPlaceholderExprSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/FixIts.swift
Labels: enhancement

#494 Store a collection of patterns to match against in Configuration.TestFilter instead of chaining multiple pattern-matcher filters
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/Running/Configuration.TestFilter.swift
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: bug, tools integration

#497 Update CMake settings to match recent package changes
  CMakeLists.txt
  Package.swift
  Sources/Testing/CMakeLists.txt
  Sources/TestingMacros/CMakeLists.txt
  cmake/modules/shared/AvailabilityDefinitions.cmake
  cmake/modules/shared/CompilerSettings.cmake
Labels: bug

#498 Avoid linker symbol de-duplication in 'failureBreakpoint()' marker function
  Sources/Testing/Issues/Issue+Recording.swift
Labels: bug

#507 Skip evaluating parameterized test arguments for disabled tests
  Sources/Testing/Running/Runner.Plan.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
Labels: bug

#509 Remove an obsolete workaround for Result.get()
  Sources/Testing/Support/Additions/ResultAdditions.swift
Labels: enhancement, workaround
