Repository swiftlang/swift-testing, pull requests merged in 2024-07, with the labels that each got.

#520 @Test applied to function with newline before its name causes error in expanded code
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug

#522 Remove 'Runner.Plan.independentlyRunnableSteps'
  Sources/Testing/Running/Runner.Plan.swift
  Tests/TestingTests/PlanTests.swift
Labels: enhancement, tools integration

#523 Avoid calling `malloc()` while holding a lock that may block dyld or libobjc.
  Sources/_TestingInternals/Discovery.cpp
Labels: bug, darwin, performance

#512 Add experimental overload of `confirmation()` that takes a range.
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/SourceAttribution/CustomTestStringConvertible.swift
  Tests/TestingTests/ConfirmationTests.swift
Labels: enhancement, public-api

#525 Remove `"(unknown context at $xxxxxxxx)"` from fully-qualified type names.
  Sources/Testing/Parameterization/TypeInfo.swift
Labels: bug

#517 Support building macro plugin as a library instead of executable via CMake
  Package.swift
  Sources/CMakeLists.txt
  Sources/Testing/CMakeLists.txt
  Sources/TestingMacros/CMakeLists.txt
  Sources/TestingMacros/TestingMacrosMain.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, swift-6

#526 Ensure that a `CustomExecutionTrait`'s teardown logic occurs _after_ nested tests run.
  Sources/Testing/Running/Runner.swift
  Tests/TestingTests/Traits/CustomExecutionTraitTests.swift
Labels: bug

#528 Avoid fork-bombing ourselves when hosted by `swift-test`.
  Sources/Testing/ExitTests/ExitTest.swift
Labels: bug, swiftpm-integration, tools integration, windows, linux, darwin

#529 Use the '-define-availability' frontend flag directly in CMake rules
  cmake/modules/shared/AvailabilityDefinitions.cmake
Labels: enhancement, tools integration

#530 Change the default JSON schema version to v0.
  Sources/Testing/EntryPoints/ABIv0/ABIv0.Record+Streaming.swift
  Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedTest.swift
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/Test.swift
Labels: enhancement, tools integration

#479 [SWT-0002] A stable JSON-based ABI for tools integration
  Documentation/ABI/JSON.md
  Documentation/Proposals/0002-json-abi.md
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/ABI/v0/ABIv0.Record+Streaming.swift
  Sources/Testing/ABI/v0/ABIv0.Record.swift
  Sources/Testing/ABI/v0/ABIv0.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedEvent.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedInstant.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedIssue.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedMessage.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedTest.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/EntryPoints/ABIEntryPoint.swift
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, swiftpm-integration, tools integration, public-api, api-proposal

#511 Emit ABIv0 JSON objects for tests when listing them.
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/ABIv0.Record+Streaming.swift
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Running/Runner.swift
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, swiftpm-integration, tools integration

#533 Do not write to `stderr` when testing `swift test list`.
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
Labels: bug

#536 Emit a specific exit code when no tests match inputs to `swift test`.
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/EntryPoints/SwiftPMEntryPoint.swift
  Sources/_TestingInternals/include/Includes.h
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, swiftpm-integration, windows, linux, darwin

#537 Silence a noisy test
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug, swiftpm-integration

#541 Work around a bug in the older Swift compiler used to build swift-syntax in the toolchain, which affected certain result builder APIs
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
Labels: workaround, build

#542 Missing newline on error in `entryPoint()`.
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
Labels: bug, swiftpm-integration

#540 Remove `Snapshot` types from non-Darwin builds.
  Package.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/ABIv0.Record+Streaming.swift
  Sources/Testing/Events/Event.swift
  Sources/Testing/Expectations/Expectation.swift
  Sources/Testing/Issues/ErrorSnapshot.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/Runner.Plan.SnapshotTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: tools integration, windows, linux, wasi/wasm

#539 Lower `Backtrace` and `SourceContext` to SPI.
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedIssue.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/SourceAttribution/SourceContext.swift
  Sources/Testing/Testing.docc/Expectations.md
Labels: bug, public-api

#545 Remove the legacy Xcode 16 entry point function on non-Darwin platforms.
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: bug, tools integration, windows, linux, wasi/wasm

#548 Lower some symbols to SPI.
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Parameterization/Test.Case.ID.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Test.swift
  Sources/Testing/Testing.docc/Documentation.md
  Sources/Testing/Traits/Comment.swift
  Sources/Testing/Traits/ConditionTrait+Macro.swift
  Sources/Testing/Traits/ConditionTrait.swift
Labels: tools integration, public-api

#549 Add skipped test tracking to JUnit output.
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
Labels: enhancement, swiftpm-integration, tools integration

#550 Allow non-`final` classes to act as suites.
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug, public-api

#553 Fix incorrect implementation-only import for CMake build
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
Labels: bug, build

#555 Ensure `&` is escaped in XML output.
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
Labels: bug, swiftpm-integration

#557 Simplify `failureBreakpoint()` and add a unit test.
  Sources/Testing/Issues/Issue+Recording.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement, tools integration, performance

#554 Remove @_implementationOnly imports guarded by 'SWT_BUILDING_WITH_CMAKE'
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/Events/Clock.swift
  Sources/Testing/Events/TimeValue.swift
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Sources/Testing/Support/CError.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/GetSymbol.swift
  Sources/Testing/Support/Locked.swift
  Sources/Testing/Support/Versions.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/DumpTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Support/CErrorTests.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
  Tests/TestingTests/TypeInfoTests.swift
  Tests/TestingTests/VariadicGenericTests.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, build

#560 Disable a couple of tests on older OSes that are reliant on `Regex`.
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug, darwin

#559 Remove `Test.Case`'s conformance to `Identifiable`.
  Sources/Testing/Parameterization/Test.Case.ID.swift
Labels: tools integration, public-api

#564 Apply `@_spi(ForToolsIntegrationOnly)` attribute to the right `isKnown` property.
  Sources/Testing/Issues/Issue.swift
Labels: bug

#567 Explicitly import Foundation in IssueTests.swift.
  Tests/TestingTests/IssueTests.swift
Labels: bug, darwin

#568 Ensure `stdout` is line-buffered when testing starts.
  Sources/Testing/ABI/EntryPoints/SwiftPMEntryPoint.swift
Labels: bug, swiftpm-integration

#569 Ensure serially-scheduled tests run in source order.
  Sources/Testing/Running/Runner.swift
  Tests/TestingTests/RunnerTests.swift
Labels: bug, concurrency

#570 `Graph.count` is computed incorrectly.
  Sources/Testing/Support/Graph.swift
  Tests/TestingTests/Support/GraphTests.swift
Labels: bug

#575 Remove "unconditional" messaging from Issue kind `.unconditional`.
  Sources/Testing/Issues/Issue.swift
Labels: bug, public-api

#576 Move the `stdout` line-buffering call.
  Sources/Testing/ABI/EntryPoints/SwiftPMEntryPoint.swift
Labels: bug, swiftpm-integration

#535 [SWT-0003] Make .serialized trait public API
  Documentation/Proposals/0003-make-serialized-trait-api.md
Labels: concurrency, public-api, api-proposal

#578 Run a subtask of the runner task group for each individual test even when running serially.
  Sources/Testing/Running/Runner.swift
Labels: bug, concurrency, darwin

#534 [SWT-0004] Constrain the granularity of test time limit durations
  Documentation/Proposals/0004-constrain-the-granularity-of-test-time-limit-durations.md
  Sources/Testing/Traits/TimeLimitTrait.swift
Labels: public-api, api-proposal

#579 Use `access()` instead of `stat()` to determine if the SF Pro font is installed.
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
Labels: bug, darwin, performance

#582 Make `Test.xcTestCompatibleSelector` `nonisolated(unsafe)` so it can be used with Xcode 15 CLTools.
  Sources/Testing/Test.swift
Labels: concurrency, darwin, workaround

#583 Add some WASI-specific branches.
  Package.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/Versions.swift
  Sources/_TestingInternals/include/Stubs.h
Labels: bug, wasi/wasm

#584 Complete WebAssembly/WASI Support
  Package.swift
  README.md
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/Locked.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Includes.h
  cmake/modules/shared/CompilerSettings.cmake
Labels: bug, enhancement, wasi/wasm
