Repository swiftlang/swift-testing, pull requests merged in 2024-11, with the labels that each got.

#770 Attachments!
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedAttachment.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedEvent.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedMessage.swift
  Sources/Testing/Attachments/Test.Attachable.swift
  Sources/Testing/Attachments/Test.Attachment.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Sources/Testing/Running/Configuration+EventHandling.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/AttachmentTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, swiftpm-integration, tools integration, public-api, attachments/activities

#797 Ensure the `Bool` overload of `__checkBinaryOperation()` is still preferred.
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug, issue-handling

#796 Attachments! [Take 2]
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedAttachment.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedEvent.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedMessage.swift
  Sources/Testing/Attachments/Test.Attachable.swift
  Sources/Testing/Attachments/Test.Attachment.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Sources/Testing/Running/Configuration+EventHandling.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/AttachmentTests.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, swiftpm-integration, tools integration, public-api, attachments/activities

#800 WASI: Access to `EEXIST` through a stub getter function
  Sources/Testing/Attachments/Test.Attachment.swift
  Sources/_TestingInternals/include/Stubs.h
Labels: bug, wasi/wasm

#803 Test cleanup: Remove an obsolete fixture suite and add .hidden to a few tests
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/PlanTests.swift
Labels: bug

#801 Specify the module to find the ABI entry point function in (in our own tests).
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: bug, darwin, workaround

#806 Fix a crash when describing a confirmation failure with a range.
  Sources/Testing/Issues/Issue.swift
  Tests/TestingTests/ConfirmationTests.swift
Labels: bug

#807 Add support for platform-specific unconditional availability.
  Sources/Testing/Traits/ConditionTrait+Macro.swift
  Sources/TestingMacros/Support/Additions/WithAttributesSyntaxAdditions.swift
  Sources/TestingMacros/Support/AvailabilityGuards.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: bug

#790 Do not perform full expansion of `#expect()` when `try` or `await` is present.
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug

#809 Eagerly move attachable values to the heap.
  Sources/Testing/Attachments/Test.Attachment.swift
  Tests/TestingTests/AttachmentTests.swift
Labels: enhancement, performance, attachments/activities

#810 Revert "Eagerly move attachable values to the heap. (#809)"
  Sources/Testing/Attachments/Test.Attachment.swift
  Tests/TestingTests/AttachmentTests.swift
Labels: self-reviewed

#812 Provide an environment flag to disable error backtrace capturing.
  Sources/Testing/SourceAttribution/Backtrace.swift
Labels: enhancement, workaround, performance, issue-handling

#811 Provide an opt-out conditional for lazy attachment encoding.
  Sources/Testing/Attachments/Test.Attachment.swift
Labels: enhancement, workaround, embedded-swift, attachments/activities

#792 Update install to ensure the build directory is not added to the rpath
  cmake/modules/SwiftModuleInstallation.cmake
Labels: bug, build

#816 Work around Windows build failure due to SwiftPM regression.
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: bug, windows, workaround, build

#815 Fix how we check if a range expression covers one value.
  Sources/Testing/Issues/Issue.swift
  Tests/TestingTests/ConfirmationTests.swift
Labels: bug, issue-handling

#814 Make `Test.Attachment` generic.
  Documentation/Proposals/0005-ranged-confirmations.md
  Package.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedAttachment.swift
  Sources/Testing/Attachments/Test.Attachable.swift
  Sources/Testing/Attachments/Test.AttachableContainer.swift
  Sources/Testing/Attachments/Test.Attachment.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Events/Event.swift
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Running/Configuration+EventHandling.swift
  Tests/TestingTests/AttachmentTests.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, embedded-swift, attachments/activities

#817 SourceLocation.init should enforce valid arguments
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/SourceAttribution/SourceLocation.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/SourceLocationTests.swift
Labels: enhancement

#821 Hoist `Attachment` and `Attachable` out of `Test`.
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedAttachment.swift
  Sources/Testing/Attachments/Attachable.swift
  Sources/Testing/Attachments/AttachableContainer.swift
  Sources/Testing/Attachments/Attachment.swift
  Sources/Testing/Attachments/Test.Attachable.swift
  Sources/Testing/Attachments/Test.AttachableContainer.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Events/Event.swift
  Tests/TestingTests/AttachmentTests.swift
Labels: public-api, attachments/activities

#822 Update DocC symbol references for `Attachment` _et al._
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedAttachment.swift
  Sources/Testing/Attachments/Attachable.swift
  Sources/Testing/Attachments/AttachableContainer.swift
  Sources/Testing/Attachments/Attachment.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
Labels: bug, documentation, attachments/activities

#820 Defer the recursive propagation of suite traits until after filtering
  Sources/Testing/Running/Configuration.TestFilter.swift
  Sources/Testing/Running/Runner.Plan.swift
  Tests/TestingTests/PlanTests.swift
Labels: enhancement, performance

#407 Ensure tests representing containing types of suites are synthesized if necessary
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Test+Discovery.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: bug, enhancement, performance

#829 Fix a non-portable target reference in CMake helper function
  cmake/modules/SwiftModuleInstallation.cmake
Labels: bug, build

#823 Expand the 'Known Issues' documentation article
  Sources/Testing/Issues/KnownIssue.swift
  Sources/Testing/Testing.docc/known-issues.md
Labels: documentation, enhancement, issue-handling

#831 [6.1] Remove '-dev' from package version
  cmake/modules/LibraryVersion.cmake
Labels: bug

#830 [release/6.0] Testing: add some force unwraps for Android
  Sources/Testing/Support/FileHandle.swift
Labels: bug, android

#832 [6.0] Update install to ensure the build directory is not added to the rpath
  cmake/modules/SwiftModuleInstallation.cmake
Labels: bug, build
