Repository swiftlang/swift-testing, pull requests merged in 2024-01, with the labels that each got.

#158 Update MigratingFromXCTest making it clear you must import Testing.
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
Labels: documentation

#172 Fix syntax of `#expect(throws:)` example in documentation
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
Labels: documentation

#173 Add a (very) short example test to the repo readme.
  README.md
Labels: documentation

#175 Work around macro expansion bug in 2024-1-4 toolchain.
  Tests/TestingTests/Runner.Plan.SnapshotTests.swift
Labels: workaround

#174 Parallelize tests by default.
  Sources/Testing/Running/EntryPoint.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, concurrency, swiftpm-integration

#177 Don't shadow `VersionTupleSyntax.components`.
  Sources/TestingMacros/Support/Additions/VersionTupleSyntaxAdditions.swift
  Sources/TestingMacros/Support/AvailabilityGuards.swift
Labels: enhancement

#178 Remove `Test.underestimatedCaseCount` SPI
  Sources/Testing/Test.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement

#181 Remove `--enable-experimental-swift-testing` from the Getting Started doc.
  Sources/Testing/Testing.docc/TemporaryGettingStarted.md
Labels: documentation, swiftpm-integration

#182 Fix an incomplete comment.
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
Labels: documentation

#185 `Locked` shouldn't be a property wrapper.
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
  Sources/Testing/Issues/Confirmation.swift
  Sources/Testing/Issues/KnownIssue.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/Locked.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/Support/LockTests.swift
Labels: concurrency, workaround

#184 Console output should prefix messages with "Suite" instead of "Test" for suites
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: enhancement

#194 Rename `Test.ParameterInfo` to `Test.Parameter`
  Sources/Testing/Parameterization/CustomTestArgumentEncodable.swift
  Sources/Testing/Parameterization/Test.Case.Generator.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement, public-api

#191 Remove the 'ExperimentalParameterizedTesting' `@_spi` group from several parameterized testing-related declarations
  Sources/Testing/Events/Event.swift
  Sources/Testing/Parameterization/CustomTestArgumentEncodable.swift
  Sources/Testing/Parameterization/Test.Case.ID.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
  Tests/TestingTests/ZipTests.swift
Labels: enhancement, public-api

#180 Optionally capture source code representations for all traits.
  Sources/Testing/Testing.docc/AddingTags.md
  Sources/Testing/Testing.docc/DefiningTests.md
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/Testing/Traits/Tag+Macro.swift
  Sources/Testing/Traits/Tag.List.swift
  Sources/Testing/Traits/Tag.swift
  Sources/Testing/Traits/Trait.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, public-api

#198 Work around a bug with variadic generics when mixed with C strings.
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/TestingInternals/include/Stubs.h
  Sources/TestingInternals/include/TestSupport.h
  Tests/TestingTests/VariadicGenericTests.swift
Labels: bug, workaround
