Repository swiftlang/swift-testing, pull requests merged in 2024-04, with the labels that each got.

#322 Enable `pthread_mutex_t` use on WASI with a multithreaded runtime.
  Sources/Testing/Support/Locked.swift
Labels: enhancement, concurrency, wasi/wasm

#279 Adopt `lexicalContext` from swift-syntax-6.0.0.
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingTests/RunnerTests.swift
Labels: enhancement, swift-6

#323 Make `Event.ConsoleOutputRecorder.Option[s]` a struct instead of an enum.
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: bug, tools integration

#327 Specialize `FileHandle.write(_:)` when the input is `UnsafeBufferPointer<UInt8>`.
  Sources/Testing/Support/FileHandle.swift
Labels: enhancement, performance

#326 Add a dedicated `Win32Error` type for errors in the Windows domain.
  Sources/Testing/Support/CError.swift
  Sources/Testing/Support/Environment.swift
  Sources/TestingInternals/include/Stubs.h
  Tests/TestingTests/Support/CErrorTests.swift
Labels: enhancement, windows

#325 Use `String(reflecting:)` instead of `_typeName(_:qualified:)` to get the fully-qualified names of types.
  Sources/Testing/Parameterization/TypeInfo.swift
  Tests/TestingTests/TypeInfoTests.swift
Labels: bug

#331 Add a note about compile-time diagnostics to the style guide.
  Documentation/StyleGuide.md
Labels: documentation, enhancement

#330 Fix spelling of a new swift-syntax-600-only diagnostic.
  Sources/TestingMacros/Support/DiagnosticMessage.swift
Labels: bug

#332 Diagnose when a test or suite is embedded in a non-final class.
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
Labels: bug, public-api

#333 Disallow test/suite declarations in protocols.
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
Labels: bug, swift-6

#334 Use `lexicalContext` to improve diagnostics for tag declarations.
  Sources/Testing/Traits/Tags/Tag+Macro.swift
  Sources/Testing/Traits/Tags/Tag.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TagMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TagMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: bug, swift-6

#336 Apply suite diagnostics to the entire lexical context.
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/Additions/WithAttributesSyntaxAdditions.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
Labels: bug, swift-6

#337 Prevent adding tests to extensions to generic types.
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
Labels: bug, swift-6

#305 Improve handling of required expectation failures in error matcher closure of `#expect { } throws: { }`
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Running/Runner.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug, enhancement

#339 Avoid reassigning task-local runtime state in a Runner's event handler unless it's nested
  Sources/Testing/Running/Runner.RuntimeState.swift
  Tests/TestingTests/Runner.RuntimeStateTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: bug

#307 Add experimental exit test support.
  Package.swift
  Package@swift-6.0.swift
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Sources/Testing/Support/SystemError.swift
  Sources/Testing/Test+Discovery.swift
  Sources/TestingInternals/Discovery.cpp
  Sources/TestingInternals/include/Discovery.h
  Sources/TestingInternals/include/Includes.h
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestingMacrosMain.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, public-api, swift-6

#341 Add internal function to get the entire environment block.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/Environment.swift
  Sources/TestingInternals/include/Includes.h
  Sources/TestingInternals/include/Stubs.h
  Tests/TestingTests/Support/EnvironmentTests.swift
Labels: enhancement

#321 Extend existing Snapshot types and introduce new ones for Event.Context
  Sources/Testing/Events/Event.swift
  Sources/Testing/Expectations/Expectation.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Test.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
Labels: tools integration

#349 Some minor exit test refinements.
  Sources/Testing/ExitTests/ExitTest.swift
Labels: bug

#350 Fix dead code following #349.
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Running/XCTestScaffold.swift
Labels: bug

#351 Only store Mach header addresses for images containing Swift data.
  Sources/TestingInternals/Discovery.cpp
Labels: bug, darwin

#352 Remove the new diagnostic added in #302.
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/PlanTests.swift
  Tests/TestingTests/Runner.Plan.SnapshotTests.swift
  Tests/TestingTests/RunnerTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
Labels: bug

#354 Remove exit tests' dependency on `Process`.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/TestingInternals/include/Includes.h
  Sources/TestingInternals/include/Stubs.h
Labels: bug, windows, linux, darwin

#355 Abstract away our dependency on Foundation for JSON encoding/decoding
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Parameterization/CustomTestArgumentEncodable.swift
  Sources/Testing/Running/EntryPoint.swift
  Sources/Testing/Support/JSON.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/TestingInternals/include/Includes.h
  Tests/TestingTests/BacktraceTests.swift
  Tests/TestingTests/ClockTests.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Runner.Plan.SnapshotTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/Test.SnapshotTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/Traits/BugTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, tools integration

#356 Remove dependencies on Foundation's file handling APIs.
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/TestingInternals/include/Includes.h
  Tests/TestingTests/Support/FileHandleTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: bug, tools integration

#357 Only block a single thread on Linux (and none on Windows) when waiting for exit tests.
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Support/Locked.swift
  Sources/TestingInternals/include/Stubs.h
Labels: bug, windows, linux, performance

#362 Fix the Linux build using the 5.10 toolchain.
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/TestingInternals/include/Stubs.h
Labels: bug, linux

#361 Block tests/suites in extensions to syntactic sugar types (`[T]`, `[T:U]`, `T?`)
  Package.swift
  Package@swift-6.0.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, swift-6

#363 Fix build failures on iOS
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: bug

#347 Require that `.bug()` identifiers be parseable as URLs.
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Testing.docc/AssociatingBugs.md
  Sources/Testing/Testing.docc/BugIdentifiers.md
  Sources/TestingMacros/Support/Additions/EditorPlaceholderExprSyntaxAdditions.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
Labels: bug, public-api

#364 Unlock expression expansions for negated expressions.
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/SourceAttribution/Expression+Macro.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/SourceCodeCapturing.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingTests/IssueTests.swift
Labels: enhancement

#365 Improve type-checking time of `listTestsForSwiftPM`
  Sources/Testing/Running/EntryPoint.swift
Labels: enhancement, performance

#367 Fix thread name length in exit tests' call to `pthread_setname_np()`.
  Sources/Testing/ExitTests/WaitFor.swift
Labels: bug, linux

#370 Ignore the .vscode folder created by Visual Studio Code.
  .gitignore
Labels: bug, tools integration

#369 Fix a Linux bug where an error during `waitid()` could cause us to miss a continuation.
  Sources/Testing/ExitTests/WaitFor.swift
Labels: bug, linux, darwin

#372 Change Graph's 'mapValues' APIs to pass key path in addition to value to transform closure
  Sources/Testing/Running/Configuration.TestFilter.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Support/Graph.swift
  Tests/TestingTests/Support/GraphTests.swift
Labels: enhancement

#314 Add documentation for numeric value comparison within specified accuracy #165
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
Labels: documentation, enhancement

#374 Use `_NSGetExecutablePath()` instead of `proc_pidpath()` to get the main executable path.
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
Labels: bug, darwin, performance

#375 Missing cast to `DWORD` on Windows.
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
Labels: bug, windows

#378 Revert "Stop using the `SWIFT_PM_SUPPORTS_SWIFT_TESTING` flag. (#376)"
  Sources/Testing/Running/XCTestScaffold.swift
  Tests/TestingMacrosTests/TestSupport/Scaffolding.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/TestSupport/Scaffolding.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: bug

#379 Work around issue parsing macro declarations with other attributes.
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Test+Macro.swift
Labels: bug, workaround, swift-6

#360 Provide an ABI-friendly entry point function that takes/produces JSON.
  Sources/Testing/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Sources/Testing/Support/Versions.swift
  Sources/TestingInternals/GetSymbol.cpp
  Sources/TestingInternals/include/GetSymbol.h
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, swiftpm-integration, tools integration

#371 Relax the restrictions on exit tests running in the background.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: bug, concurrency

#338 Adopt swift-syntax-600.
  Package.swift
  Package@swift-6.0.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/Testing/Traits/Tags/Tag+Macro.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TagMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TagMacroTests.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingTests/Traits/TagListTests.swift
Labels: enhancement, swift-6

#380 Re-enable some pre-swift-syntax-600 code.
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Sources/TestingMacros/TagMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TagMacroTests.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
Labels: bug, workaround

#373 Rename `Expression` to `__Expression`.
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/Expectation.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/SourceAttribution/Expression+Macro.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Sources/Testing/Testing.docc/Expectations.md
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/SourceCodeCapturing.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/IssueTests.swift
Labels: bug, tools integration

#381 Work around miscompilation of entry point function on Windows with Swift 5.10.
  Sources/Testing/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: bug, tools integration, windows, workaround

#382 Work around miscompilation of entry point function on Windows with Swift 5.10 (Take 2).
  Sources/Testing/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/XCTestScaffold.swift
Labels: bug, tools integration, windows, workaround

#366 Lazily evaluate test arguments only after determining their test will run, and support throwing expressions
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Test.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: enhancement

#385 Rename `.serial` to `.serialized`.
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Testing.docc/Parallelization.md
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Traits/ParallelizationTrait.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/Traits/ParallelizationTraitTests.swift
Labels: enhancement, public-api

#384 Move `__swiftPMEntryPoint()` to its own file.
  Sources/Testing/EntryPoints/EntryPoint.swift
  Sources/Testing/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, tools integration
