Repository swiftlang/swift-testing, pull requests merged in 2025-10, with the labels that each got.

#1346 AdvancedConsoleOutputRecorderTests is missing an import of Foundation
  Tests/TestingTests/AdvancedConsoleOutputRecorderTests.swift
Labels: bug, build, command-line experience

#1349 Normalize the order in which we specify our Linux/FreeBSD/OpenBSD checks.
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Support/Locked+Platform.swift
  Sources/Testing/Support/Versions.swift
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: build, openbsd, tech-debt

#1352 Get exit tests functioning on OpenBSD.
  Sources/Testing/ExitTests/SpawnProcess.swift
Labels: bug, exit-tests, openbsd

#1351 Adopt `Mutex`.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Support/Locked+Platform.swift
  Sources/Testing/Support/Locked.swift
  Tests/TestingTests/Support/LockTests.swift
Labels: enhancement, concurrency, performance, tech-debt

#1353 Revert "Adopt `Mutex`."
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Support/Locked+Platform.swift
  Sources/Testing/Support/Locked.swift
  Tests/TestingTests/Support/LockTests.swift
Labels: bug, build

#1319 Attachment lifetimes
  Sources/Testing/Attachments/Attachable.swift
  Sources/Testing/Attachments/AttachableWrapper.swift
  Sources/Testing/Attachments/Attachment.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Events/Event.swift
  Sources/Testing/Running/Configuration+EventHandling.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Sources/Testing/Traits/AttachmentSavingTrait.swift
  Tests/TestingTests/Traits/AttachmentSavingTraitTests.swift
Labels: enhancement, public-api, issue-handling, attachments/activities, traits
