Repository swiftlang/swift-testing, pull requests merged in 2025-03, with the labels that each got.

#988 Diagnose when using a non-escapable type as suite.
  Sources/TestingMacros/Support/Additions/TypeSyntaxProtocolAdditions.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
Labels: enhancement

#991 Suppress `.unsafeFlags()` in Package.swift when tagging for release.
  Package.swift
Labels: bug, tools integration, build

#990 [6.1] Note in documentation when `#expect(throws:)` started returning a value.
  Sources/Testing/Expectations/Expectation+Macro.swift
Labels: documentation

#992 [6.1] Diagnose when using a non-escapable type as suite.
  Sources/TestingMacros/Support/Additions/TypeSyntaxProtocolAdditions.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
Labels: enhancement

#993 [6.1] Suppress `.unsafeFlags()` in Package.swift when tagging for release.
  Package.swift
Labels: bug, tools integration, embedded-swift, build

#976 Relocate the proposal template to swift-evolution and update documentation accordingly
  Documentation/Proposals/0000-proposal-template.md
  Documentation/Proposals/0001-refactor-bug-inits.md
  Documentation/Proposals/0002-json-abi.md
  Documentation/Proposals/0003-make-serialized-trait-api.md
  Documentation/Proposals/0004-constrain-the-granularity-of-test-time-limit-durations.md
  Documentation/Proposals/0005-ranged-confirmations.md
  Documentation/Proposals/0006-return-errors-from-expect-throws.md
  Documentation/Proposals/0007-test-scoping-traits.md
  Documentation/README.md
Labels: documentation, api-proposal

#994 Disable snapshot types on Android.
  Package.swift
Labels: bug, tools integration, android

#982 Begin installing textual .swiftinterface instead of binary .swiftmodule in toolchain builds for non-Apple platforms
  cmake/modules/SwiftModuleInstallation.cmake
Labels: enhancement, build

#981 Add a new _TestDiscovery library/target.
  Documentation/ABI/TestContent.md
  Package.swift
  Sources/CMakeLists.txt
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Discovery+Macro.swift
  Sources/Testing/Discovery.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/Additions/WinSDKAdditions.swift
  Sources/Testing/Support/GetSymbol.swift
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/Testing/Test+Discovery.swift
  Sources/_TestDiscovery/Additions/WinSDKAdditions.swift
  Sources/_TestDiscovery/CMakeLists.txt
  Sources/_TestDiscovery/DiscoverableAsTestContent.swift
  Sources/_TestDiscovery/SectionBounds.swift
  Sources/_TestDiscovery/TestContentRecord.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement, tools integration, build

#971 build: restructure the installation location
  CMakeLists.txt
  cmake/modules/PlatformInfo.cmake
  cmake/modules/SwiftModuleInstallation.cmake
Labels: build

#999 build: update missed callsites of `get_swift_testing_install_lib_dir`
  Sources/_TestDiscovery/CMakeLists.txt
  Sources/_TestingInternals/CMakeLists.txt
Labels: bug, build

#1002 [CMake] Fix quote in a generator expression
  CMakeLists.txt
Labels: bug, build

#1003 Fix some broken links in Documentation
  Documentation/ABI/JSON.md
  Documentation/WASI.md
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
Labels: documentation

#1004 Raise `types(withNamesContaining:)` to SPI rather than `package`.
  Sources/_TestDiscovery/TestContentRecord.swift
Labels: tools integration

#1005 Remove the "Result" section of this project's Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#1010 Refine type-based test discovery mechanism to use test content records.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/Testing/Test+Discovery.swift
  Sources/TestingMacros/CMakeLists.txt
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/Additions/IntegerLiteralExprSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/TokenSyntaxAdditions.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/TestContentGeneration.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Sources/_TestDiscovery/TestContentRecord.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/TypeNameConflictTests.swift
Labels: enhancement, tools integration, exit-tests

#1008 Add ConditionTraitTests to cover the Swift 6.0 compiler issue for custom trait + closure + macro
  Tests/TestingTests/Traits/ConditionTraitTests.swift
Labels: enhancement, workaround, traits

#880 Store test content in a custom metadata section.
  Documentation/Porting.md
  Package.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/Testing/Test+Discovery.swift
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/TestContentGeneration.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Sources/_TestDiscovery/SectionBounds.swift
  Sources/_TestDiscovery/TestContentRecord.swift
  Sources/_TestingInternals/Discovery.cpp
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement, tools integration, windows, linux, darwin, performance, embedded-swift, wasi/wasm, android, freebsd, less-c++

#1015 Fix crash when loading test content records from the type metadata section.
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Sources/_TestDiscovery/DiscoverableAsTestContent.swift
  Sources/_TestDiscovery/TestContentRecord.swift
Labels: bug, workaround, self-reviewed

#1020 Enable upcoming feature 'MemberImportVisibility' and fix issues it reveals
  Package.swift
  Sources/Testing/ABI/ABI.Record+Streaming.swift
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/PragmaMacro.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift
  Sources/TestingMacros/Support/Additions/TokenSyntaxAdditions.swift
  Sources/TestingMacros/Support/Argument.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/AvailabilityGuards.swift
  Sources/TestingMacros/Support/CommentParsing.swift
  Sources/TestingMacros/Support/ConditionArgumentParsing.swift
  Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/Support/SourceCodeCapturing.swift
  Sources/TestingMacros/Support/SourceLocationGeneration.swift
  Sources/TestingMacros/Support/TestContentGeneration.swift
  Sources/TestingMacros/TagMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/PragmaMacroTests.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingTests/AttachmentTests.swift
Labels: enhancement, build

#1018 Don't emit `@_section` attributes unless the macro target has `SymbolLinkageMarkers`.
  Sources/TestingMacros/Support/TestContentGeneration.swift
Labels: tools integration, build, macros, discovery

#1019 Add a dedicated `TestContentKind` type to `_TestDiscovery`.
  Documentation/ABI/TestContent.md
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Test+Discovery.swift
  Sources/TestingMacros/Support/TestContentGeneration.swift
  Sources/_TestDiscovery/CMakeLists.txt
  Sources/_TestDiscovery/DiscoverableAsTestContent.swift
  Sources/_TestDiscovery/TestContentKind.swift
  Sources/_TestDiscovery/TestContentRecord.swift
  Tests/TestingTests/DiscoveryTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement, tools integration, discovery

#1017 Add a `reserved` argument to the test content record accessor signature.
  Documentation/ABI/TestContent.md
  Sources/Testing/Discovery+Macro.swift
  Sources/TestingMacros/ConditionMacro.swift
  Sources/TestingMacros/SuiteDeclarationMacro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Sources/_TestDiscovery/TestContentRecord.swift
  Tests/TestingTests/DiscoveryTests.swift
Labels: enhancement, tools integration

#1022 Enable 'MemberImportVisibility' upcoming feature in CMake rules
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, build

#1023 Continue encoding value for deprecated property in runner plan snapshot to avoid decoding error in clients
  Sources/Testing/Running/Runner.Plan.swift
Labels: bug, tools integration, workaround

#1025 build: avoid doubly nesting the swift module
  CMakeLists.txt
Labels: bug, build

#1000 Represent non-encodable test argument values in Test.Case.ID
  Sources/Testing/ABI/Encoded/ABI.EncodedTest.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Parameterization/CustomTestArgumentEncodable.swift
  Sources/Testing/Parameterization/Test.Case.Generator.swift
  Sources/Testing/Parameterization/Test.Case.ID.swift
  Sources/Testing/Parameterization/Test.Case.swift
  Tests/TestingTests/EventTests.swift
  Tests/TestingTests/Test.Case.Argument.IDTests.swift
  Tests/TestingTests/Test.Case.ArgumentTests.swift
  Tests/TestingTests/Test.Case.GeneratorTests.swift
  Tests/TestingTests/Test.CaseTests.swift
  Tests/TestingTests/TestCaseSelectionTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement, tools integration, parameterized-testing

#1012 Rewrite static section bounds discovery in Swift.
  Documentation/Porting.md
  Sources/_TestDiscovery/SectionBounds.swift
  Sources/_TestDiscovery/TestContentRecord.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Discovery.h
Labels: enhancement, darwin, embedded-swift, wasi/wasm, less-c++, discovery

#1030 build: account for spaces in the toolchain
  Sources/CMakeLists.txt
Labels: bug, windows, build

#1032 Change `Attachment.attach()` to `Attachment.record()` and `Attachable.withUnsafeBufferPointer()` to `Attachable.withUnsafeBytes()`.
  Package.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/_AttachableImageContainer.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Attachable+Encodable+NSSecureCoding.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Attachable+Encodable.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Attachable+NSSecureCoding.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Data+Attachable.swift
  Sources/Overlays/_Testing_Foundation/Attachments/_AttachableURLContainer.swift
  Sources/Testing/Attachments/Attachable.swift
  Sources/Testing/Attachments/AttachableContainer.swift
  Sources/Testing/Attachments/Attachment.swift
  Tests/TestingTests/AttachmentTests.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, public-api, attachments/activities

#1033 Work around a compiler crash building `Attachment.record()`.
  Sources/Testing/Attachments/Attachment.swift
Labels: workaround, public-api, attachments/activities

#1035 Ensure `Locked+Platform.swift` is not stripped when statically linking.
  Sources/Testing/Support/Locked+Platform.swift
  Sources/Testing/Support/Locked.swift
Labels: bug, concurrency, workaround, embedded-swift

#1036 Remove unused "override comment" from ConditionTrait implementation
  Sources/Testing/Traits/ConditionTrait.swift
Labels: enhancement, traits

#1038 Qualify `@__testing(warning:)` usage in macro expansion with module name and enhance a related unit test
  Sources/TestingMacros/Support/TestContentGeneration.swift
  Tests/TestingMacrosTests/PragmaMacroTests.swift
Labels: enhancement, macros

#909 Add ConditionTrait.evaluate()
  Sources/Testing/Traits/ConditionTrait.swift
  Tests/TestingTests/Traits/ConditionTraitTests.swift
Labels: enhancement, public-api, api-proposal

#1045 🍒6.1: [CMake] Set CMP0157 to OLD when targeting Android with the Windows toolchain (#1009)
  CMakeLists.txt
Labels: windows, build

#1044 Erase environment variables set by exit tests after reading them.
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/Environment.swift
  Tests/TestingTests/Support/EnvironmentTests.swift
Labels: bug, exit-tests

#1042 Pause child processes on spawn.
  Sources/Testing/ExitTests/SpawnProcess.swift
Labels: windows, darwin, exit-tests
