Repository swiftlang/swift-testing, pull requests merged in 2025-01, with the labels that each got.

#877 [docs] Correct the link of Proposal SWT-0006
  Documentation/Proposals/0006-return-errors-from-expect-throws.md
Labels: bug, documentation

#881 Remove the `introduced: 6.0` argument from the to-be-deprecated attributes on `#expect(performing:throws:)` and `#require(performing:throws:)`.
  Documentation/Proposals/0006-return-errors-from-expect-throws.md
  Sources/Testing/Expectations/Expectation+Macro.swift
Labels: bug, documentation, public-api, self-reviewed

#889 [6.1] Remove the `introduced: 6.0` argument from the to-be-deprecated attributes on `#expect(performing:throws:)` and `#require(performing:throws:)`.
  Documentation/Proposals/0006-return-errors-from-expect-throws.md
  Sources/Testing/Expectations/Expectation+Macro.swift
Labels: bug, documentation, public-api

#890 Add speculative support for OpenBSD.
  Documentation/Porting.md
  Package.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Attachment+URL.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/EntryPoints/SwiftPMEntryPoint.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/SourceAttribution/Backtrace+Symbolication.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
  Sources/Testing/Support/CError.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/FileHandle.swift
  Sources/Testing/Support/GetSymbol.swift
  Sources/Testing/Support/Locked.swift
  Sources/Testing/Support/Versions.swift
  Sources/Testing/Traits/Tags/Tag.Color+Loading.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Includes.h
  Sources/_TestingInternals/include/Stubs.h
  Tests/TestingTests/Support/EnvironmentTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: enhancement, help wanted, openbsd

#882 Revert "Work around a crash importing FoundationXML. (#786)"
  Tests/TestingTests/EventRecorderTests.swift
Labels: workaround

#892 Use the Toolhelp32 API to enumerate loaded Win32 modules.
  Sources/Testing/Support/Additions/WinSDKAdditions.swift
  Sources/Testing/Support/GetSymbol.swift
Labels: enhancement, windows

#893 Discover test content stored in the test content section of loaded images.
  Documentation/ABI/TestContent.md
  Package.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Discovery+Platform.swift
  Sources/Testing/Discovery.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/Additions/WinSDKAdditions.swift
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/Testing/Test+Discovery.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Discovery.h
  Sources/_TestingInternals/include/Includes.h
  Sources/_TestingInternals/include/Stubs.h
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement, tools integration, windows, linux, darwin, performance, embedded-swift, wasi/wasm, android, freebsd, openbsd

#895 Add an attribute that emits a warning.
  Sources/Testing/Test+Macro.swift
  Sources/TestingMacros/PragmaMacro.swift
  Tests/TestingMacrosTests/PragmaMacroTests.swift
  Tests/TestingMacrosTests/TestSupport/Parse.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement, workaround, build

#896 Add a missing `#if !SWT_NO_EXIT_TESTS`.
  Sources/Testing/Test+Discovery+Legacy.swift
Labels: bug, darwin, wasi/wasm, build, exit-tests, android

#733 [SWT-NNNN] Introduce API allowing traits to customize test execution
  Documentation/Proposals/NNNN-custom-test-execution-traits.md
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Testing.docc/Traits/Trait.md
  Sources/Testing/Traits/Trait.swift
  Tests/TestingTests/Traits/CustomExecutionTraitTests.swift
  Tests/TestingTests/Traits/TestScopingTraitTests.swift
Labels: documentation, enhancement, public-api, api-proposal

#897 Fix statically-linked platforms building new test content discovery code.
  Sources/Testing/Discovery+Platform.swift
  Sources/_TestingInternals/include/Discovery.h
Labels: bug, workaround, wasi/wasm, build

#898 Use `Never` instead of `Void` as the fallback lock/mutex type.
  Sources/Testing/Support/Locked.swift
Labels: bug, workaround, wasi/wasm

#900 Assign "Test Scoping Traits" proposal a number
  Documentation/Proposals/0007-test-scoping-traits.md
Labels: documentation, api-proposal

#899 Fix several compile-time warnings that have snuck in.
  Package.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: bug, build

#887 Add support for raw identifiers.
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/SourceAttribution/SourceLocation.swift
  Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift
  Sources/TestingMacros/Support/Additions/TokenSyntaxAdditions.swift
  Sources/TestingMacros/Support/AttributeDiscovery.swift
  Sources/TestingMacros/Support/DiagnosticMessage.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingMacrosTests/TestDeclarationMacroTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/SourceLocationTests.swift
  Tests/TestingTests/TypeInfoTests.swift
Labels: enhancement, tools integration

#901 Remove SPIAwareTrait and adopt TestScoping in its place
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Traits/ParallelizationTrait.swift
  Sources/Testing/Traits/SPIAwareTrait.swift
  Tests/TestingTests/Traits/ParallelizationTraitTests.swift
Labels: enhancement, traits

#902 Remove C++-based section discovery logic.
  Documentation/Porting.md
  Sources/Testing/Discovery+Platform.swift
  Sources/Testing/Discovery.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/Testing/Test+Discovery.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Discovery.h
Labels: enhancement

#907 [6.1] [SWT-0007] Introduce API allowing traits to customize test execution
  Documentation/Proposals/0007-test-scoping-traits.md
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Testing.docc/Traits/Trait.md
  Sources/Testing/Traits/Trait.swift
  Tests/TestingTests/Traits/CustomExecutionTraitTests.swift
  Tests/TestingTests/Traits/TestScopingTraitTests.swift
Labels: documentation, enhancement, public-api, api-proposal

#905 Remove some remnants of the C++ section discovery code that we no longer need.
  Sources/Testing/Discovery+Platform.swift
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/Versions.cpp
  Sources/_TestingInternals/include/Discovery.h
Labels: enhancement

#910 Remove @dennisweissmann from CODEOWNERS
  CODEOWNERS
Labels: documentation

#911 Update README.md's note about development toolchain requirements.
  README.md
Labels: bug, documentation

#912 Don't capture arguments to `#expect(exitsWith:)` during macro expansion.
  Documentation/ABI/TestContent.md
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: bug, exit-tests

#914 Refactor test content discovery to produce a sequence.
  Sources/Testing/Discovery+Platform.swift
  Sources/Testing/Discovery.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Test+Discovery.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement

#917 Revert #916 and apply a slightly different change.
  Sources/Testing/Discovery.swift
Labels: bug, wasi/wasm, build

#915 Limit the amount of value reflection data expectation checking collects by default
  Sources/Testing/Parameterization/Test.Case.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Tests/TestingTests/Expression.ValueTests.swift
Labels: enhancement, tools integration, performance

#918 Don't allocate a buffer on the heap when enumerating type metadata.
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Discovery.h
Labels: enhancement, performance

#919 Remove arm64e ptrauth resigning from test content discovery.
  Sources/Testing/Discovery.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Discovery.h
  Sources/_TestingInternals/include/Includes.h
Labels: bug, darwin, less-c++

#921 [TestingMacros] Remove reference to implicit backtracing import.
  Sources/TestingMacros/CMakeLists.txt
Labels: build

#920 Make all test content types directly conform to `TestContent`.
  Documentation/ABI/TestContent.md
  Sources/Testing/Discovery+Platform.swift
  Sources/Testing/Discovery.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Test+Discovery.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: enhancement, tools integration

#929 Remove Stubs.cpp and reimplement what it has in Swift.
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/_TestingInternals/CMakeLists.txt
  Sources/_TestingInternals/Stubs.cpp
  Sources/_TestingInternals/include/Stubs.h
Labels: linux, less-c++

#927 Declare Swift 6.1 availability for TestScoping-related APIs
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/SuiteTrait-scopeProvider-default-implementation-Self.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/TestScopeProvider.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/TestScoping-provideScope.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/TestScoping.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/Trait-scopeProvider-default-implementation-Never.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/Trait-scopeProvider-default-implementation-Self.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/Trait-scopeProvider-protocol-requirement.md
Labels: documentation, public-api, traits

#930 [6.1] Declare Swift 6.1 availability for TestScoping-related APIs
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/SuiteTrait-scopeProvider-default-implementation-Self.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/TestScopeProvider.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/TestScoping-provideScope.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/TestScoping.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/Trait-scopeProvider-default-implementation-Never.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/Trait-scopeProvider-default-implementation-Self.md
  Sources/Testing/Testing.docc/AvailabilityStubs/Traits/Trait-scopeProvider-protocol-requirement.md
Labels: documentation, public-api, traits

#928 Update Documentation/README.md to cover more files.
  Documentation/ExpectationCapture.md
  Documentation/README.md
  Documentation/Releases.md
Labels: documentation

#932 Missing an explicit include of `<mach-o/dyld.h>` on Apple platforms.
  Sources/_TestingInternals/include/Includes.h
Labels: bug, darwin, workaround

#933 Ensure the `ObjectiveC` module is visible to Discovery.swift
  Sources/Testing/Discovery+Platform.swift
Labels: bug, darwin, workaround

#925 Fix building on FreeBSD via cmake
  Sources/CMakeLists.txt
  Sources/Testing/CMakeLists.txt
  Sources/_TestingInternals/CMakeLists.txt
Labels: bug, build, freebsd

#934 Implement `CommandLine.executablePath` on all Apple platforms.
  Sources/Testing/Support/Additions/CommandLineAdditions.swift
Labels: bug, darwin

#926 [Code style] Require explicitly specified types for public properties
  Documentation/StyleGuide.md
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/ExitTests/ExitTestArtifacts.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Test.swift
Labels: documentation, enhancement
