Repository swiftlang/swift-testing, pull requests merged in 2025-02, with the labels that each got.

#938 Avoid using `String` while holding an internal libobjc lock.
  Sources/Testing/Discovery+Platform.swift
Labels: bug, darwin

#936 Update `Comment` to use `CustomTestStringConvertible` during string interpolation.
  Sources/Testing/Traits/Comment.swift
  Tests/TestingTests/Traits/CommentTests.swift
Labels: bug, public-api, issue-handling, command-line experience, traits

#939 Add a `type` argument to the ABI accessor function signature.
  Documentation/ABI/TestContent.md
  Sources/Testing/Discovery.swift
  Sources/Testing/Test+Discovery.swift
  Tests/TestingTests/MiscellaneousTests.swift
Labels: bug, tools integration

#940 Simplify statically-linked section discovery.
  Sources/Testing/Discovery+Platform.swift
  Sources/_TestingInternals/Discovery.cpp
  Sources/_TestingInternals/include/Discovery.h
Labels: less-c++

#942 Use `os_unfair_lock` on Darwin when available.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Support/Locked+Platform.swift
  Sources/Testing/Support/Locked.swift
  Sources/_TestingInternals/include/Includes.h
  Tests/TestingTests/Support/LockTests.swift
  Tests/TestingTests/Traits/ParallelizationTraitTests.swift
Labels: enhancement, concurrency, darwin, performance

#931 Introduce a severity level for issues, and a 'warning' severity
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedIssue.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedMessage.swift
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Running/Configuration+EventHandling.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Tests/TestingTests/ConfigurationTests.swift
  Tests/TestingTests/EntryPointTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Runner.RuntimeStateTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: enhancement, tools integration, issue-handling

#947 Suppress warning about `#require(nonOptional)` in some cases.
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
Labels: bug, workaround, issue-handling

#949 [6.1] Suppress warning about `#require(nonOptional)` in some cases.
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
Labels: bug, workaround, issue-handling

#945 Add a (internal-only) `CustomIssueRepresentable` protocol.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Support/CustomIssueRepresentable.swift
  Sources/Testing/Support/SystemError.swift
  Tests/TestingTests/IssueTests.swift
Labels: enhancement, issue-handling

#950 Revert "Introduce a severity level for issues, and a 'warning' severity (#931)"
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedIssue.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedMessage.swift
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Running/Configuration+EventHandling.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Tests/TestingTests/ConfigurationTests.swift
  Tests/TestingTests/EntryPointTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Runner.RuntimeStateTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: bug, workaround

#952 Introduce a severity level for issues, and a 'warning' severity (un-revert #931)
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedIssue.swift
  Sources/Testing/ABI/v0/Encoded/ABIv0.EncodedMessage.swift
  Sources/Testing/Events/Event.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/Events/Recorder/Event.Symbol.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Running/Configuration+EventHandling.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/Runner.RuntimeState.swift
  Tests/TestingTests/ConfigurationTests.swift
  Tests/TestingTests/EntryPointTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/Runner.RuntimeStateTests.swift
  Tests/TestingTests/RunnerTests.swift
Labels: enhancement, tools integration, workaround, build, issue-handling

#948 Some fixes/cleanup to TestContent.md
  Documentation/ABI/TestContent.md
Labels: bug, documentation, enhancement, tools integration

#953 Move JSON ABI source files to prepare for v1.
  Documentation/ABI/JSON.md
  Sources/Testing/ABI/ABI.Record+Streaming.swift
  Sources/Testing/ABI/ABI.Record.swift
  Sources/Testing/ABI/ABI.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedAttachment.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedBacktrace.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedError.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedEvent.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedInstant.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedIssue.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedMessage.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedTest.swift
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ABI/v0/ABIv0.swift
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/ExitTest.swift
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: tools integration

#955 Require sendable userInfo values in JSON.withEncoding(of:userInfo:_:)
  Sources/Testing/Support/JSON.swift
Labels: bug, build

#951 Enable Library Evolution in package builds for public library targets
  Package.swift
  Sources/Testing/Running/Configuration.swift
Labels: enhancement, workaround, build

#954 Declare a package name for CMake builds and remove @_spi(ForSwiftTestingOnly)
  Documentation/SPI.md
  Sources/Overlays/_Testing_CoreGraphics/Attachments/Attachment+AttachableAsCGImage.swift
  Sources/Overlays/_Testing_CoreGraphics/Attachments/ImageAttachmentError.swift
  Sources/Overlays/_Testing_Foundation/Attachments/Attachment+URL.swift
  Sources/Testing/Attachments/Attachment.swift
  Tests/TestingTests/AttachmentTests.swift
  cmake/modules/shared/CompilerSettings.cmake
Labels: enhancement, build

#959 Require sendable userInfo values in JSON.withEncoding(of:userInfo:_:)
  Sources/Testing/Support/JSON.swift
Labels: bug, build

#961 Update proposals to reflect implementation status, Swift version, and forum discussion links
  Documentation/Proposals/0001-refactor-bug-inits.md
  Documentation/Proposals/0002-json-abi.md
  Documentation/Proposals/0003-make-serialized-trait-api.md
  Documentation/Proposals/0004-constrain-the-granularity-of-test-time-limit-durations.md
  Documentation/Proposals/0005-ranged-confirmations.md
  Documentation/Proposals/0006-return-errors-from-expect-throws.md
  Documentation/Proposals/0007-test-scoping-traits.md
Labels: documentation

#962 Improve the project's GitHub Issue templates
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  .github/ISSUE_TEMPLATE/02-change-request.yml
  .github/ISSUE_TEMPLATE/03-task.yml
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, enhancement

#960 Add an overview of test serialization to the XCTest migration guide
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
Labels: documentation, enhancement, concurrency

#958 [6.1] Cleaning recently changed docs
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Testing.docc/Traits/Trait.md
  Sources/Testing/Traits/Bug.swift
  Sources/Testing/Traits/Comment.swift
  Sources/Testing/Traits/ConditionTrait.swift
  Sources/Testing/Traits/ParallelizationTrait.swift
  Sources/Testing/Traits/TimeLimitTrait.swift
  Sources/Testing/Traits/Trait.swift
Labels: documentation, public-api

#963 Corrects use of XCTAssertEqual macro in parallelization examples.
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
Labels: documentation

#965 [6.1] Add an overview of test serialization to the XCTest migration guide
  Sources/Testing/Testing.docc/MigratingFromXCTest.md
Labels: documentation, enhancement, concurrency

#956 Plumb the schema version through the JSON ABI layers.
  Sources/Testing/ABI/ABI.Record+Streaming.swift
  Sources/Testing/ABI/ABI.Record.swift
  Sources/Testing/ABI/ABI.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedAttachment.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedBacktrace.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedError.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedEvent.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedInstant.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedIssue.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedMessage.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedTest.swift
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Tests/TestingTests/ABIEntryPointTests.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, tools integration

#966 Remove references to Xcode 16 Beta 1 (just Xcode 16, please.)
  Sources/Testing/ABI/ABI.Record+Streaming.swift
  Sources/Testing/ABI/ABI.swift
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: documentation, tools integration, darwin

#967 Avoid calling `unsafeBitCast(_:to:)` to cast C function pointers.
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/SourceAttribution/Backtrace.swift
  Sources/Testing/Support/Environment.swift
  Sources/Testing/Support/GetSymbol.swift
  Sources/Testing/Support/Versions.swift
  Tests/TestingTests/ABIEntryPointTests.swift
Labels: enhancement

#968 Don't hard-code numeric representations of ABI versions.
  Sources/Testing/ABI/Encoded/ABI.EncodedTest.swift
  Sources/Testing/ABI/EntryPoints/ABIEntryPoint.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: bug, tools integration

#969 Silence a warning on the latest 6.2-dev toolchain when building a test.
  Tests/TestingTests/IssueTests.swift
Labels: bug, workaround

#970 Restrict use of a new overload of `contains()` to Apple platforms that have it.
  Tests/TestingTests/AttachmentTests.swift
Labels: bug, darwin

#972 Show the number of test cases that ran at the end of a test
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: enhancement, tools integration, command-line experience

#974 Change the return types of test content accessors and add `ExitTest.current`.
  Documentation/ABI/TestContent.md
  Sources/Testing/Discovery.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Test+Discovery+Legacy.swift
  Sources/Testing/Test+Discovery.swift
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: tools integration, public-api, exit-tests

#980 Note in documentation when `#expect(throws:)` started returning a value.
  Sources/Testing/Expectations/Expectation+Macro.swift
Labels: documentation

#975 Rename `ExitTestArtifacts` and split `ExitCondition` in twain.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/ExitCondition.swift
  Sources/Testing/ExitTests/ExitTest.Condition.swift
  Sources/Testing/ExitTests/ExitTest.Result.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/ExitTestArtifacts.swift
  Sources/Testing/ExitTests/SpawnProcess.swift
  Sources/Testing/ExitTests/StatusAtExit.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: enhancement, public-api, exit-tests

#983 Use more distinct characters for 'skip' and 'pass w/known issues' symbols
  Sources/Testing/Events/Recorder/Event.Symbol.swift
Labels: enhancement, command-line experience

#984 Add a utility tool for previewing event symbol rendering
  Package.swift
  Sources/SymbolShowcase/SymbolShowcaseMain.swift
  Sources/Testing/Events/Recorder/Event.ConsoleOutputRecorder.swift
Labels: enhancement, command-line experience

#986 JUnit XML recorder should ignore warning issues
  Sources/Testing/Events/Recorder/Event.JUnitXMLRecorder.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: bug, swiftpm-integration, tools integration, issue-handling
