Repository swiftlang/swift-testing, pull requests merged in 2025-05, with the labels that each got.

#324 Promote exit tests to API
  Sources/Testing/CMakeLists.txt
  Sources/Testing/ExitTests/ExitStatus.swift
  Sources/Testing/ExitTests/ExitTest.CapturedValue.swift
  Sources/Testing/ExitTests/ExitTest.Condition.swift
  Sources/Testing/ExitTests/ExitTest.Result.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/Testing/Testing.docc/exit-testing.md
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingTests/AttachmentTests.swift
  Tests/TestingTests/ConfirmationTests.swift
  Tests/TestingTests/DiscoveryTests.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/PlanIterationTests.swift
  Tests/TestingTests/SourceLocationTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
Labels: enhancement, tools integration, windows, linux, darwin, public-api, api-proposal, exit-tests, freebsd, openbsd

#1100 Work around a macOS CI failure
  Tests/TestingTests/IssueTests.swift
Labels: bug, workaround, build, self-reviewed

#1101 Merge 'main' branch to 'release/6.2'
  README.md
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/ExitTests/ExitStatus.swift
  Sources/Testing/ExitTests/ExitTest.CapturedValue.swift
  Sources/Testing/ExitTests/ExitTest.Condition.swift
  Sources/Testing/ExitTests/ExitTest.Result.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/ExitTests/WaitFor.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Expectations/ExpectationChecking+Macro.swift
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Issues/KnownIssue.swift
  Sources/Testing/Running/Configuration.swift
  Sources/Testing/Running/Runner.swift
  Sources/Testing/SourceAttribution/Expression.swift
  Sources/Testing/Testing.docc/Expectations.md
  Sources/Testing/Testing.docc/OrganizingTests.md
  Sources/Testing/Testing.docc/Traits.md
  Sources/Testing/Testing.docc/exit-testing.md
  Sources/Testing/Traits/ConditionTrait.swift
  Sources/Testing/Traits/IssueHandlingTrait.swift
  Sources/TestingMacros/ConditionMacro.swift
  Tests/TestingMacrosTests/ConditionMacroTests.swift
  Tests/TestingTests/AttachmentTests.swift
  Tests/TestingTests/ConfirmationTests.swift
  Tests/TestingTests/DiscoveryTests.swift
  Tests/TestingTests/EventRecorderTests.swift
  Tests/TestingTests/ExitTestTests.swift
  Tests/TestingTests/IssueTests.swift
  Tests/TestingTests/KnownIssueTests.swift
  Tests/TestingTests/PlanIterationTests.swift
  Tests/TestingTests/SourceLocationTests.swift
  Tests/TestingTests/Support/FileHandleTests.swift
  Tests/TestingTests/Traits/ConditionTraitTests.swift
  Tests/TestingTests/Traits/IssueHandlingTraitTests.swift
Labels: integration

#1103 Restore DocC `@Comment` blocks to documentation line comments
  Sources/Testing/Attachments/Attachment.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Parameterization/Test.Case.Generator.swift
  Sources/Testing/Support/CartesianProduct.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Traits/ConditionTrait.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: documentation, enhancement, self-reviewed

#1106 Work around compiler bug affecting macro decls with #if-guarded availability when building w/legacy driver
  Sources/Testing/Expectations/Expectation+Macro.swift
Labels: bug, windows, workaround, exit-tests, android, macros

#1102 Simplify usages of withTaskGroup to infer ChildTaskResult type where possible
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Traits/TimeLimitTrait.swift
  Tests/TestingTests/Support/CartesianProductTests.swift
  Tests/TestingTests/Support/LockTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: enhancement

#1108 Add missing Foundation imports to fix test build errors on iOS with MemberImportVisibility enabled
  Tests/TestingTests/ConfirmationTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/Traits/TagListTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: bug, darwin, build

#1109 Merge 'main' branch to 'release/6.2'
  Sources/Testing/Attachments/Attachment.swift
  Sources/Testing/Expectations/Expectation+Macro.swift
  Sources/Testing/Issues/Issue.swift
  Sources/Testing/Parameterization/Test.Case.Generator.swift
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Support/CartesianProduct.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Test+Macro.swift
  Sources/Testing/Traits/ConditionTrait.swift
  Sources/Testing/Traits/TimeLimitTrait.swift
  Tests/TestingTests/ConfirmationTests.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/Support/CartesianProductTests.swift
  Tests/TestingTests/Support/LockTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
  Tests/TestingTests/Traits/TagListTests.swift
  Tests/TestingTests/Traits/TimeLimitTraitTests.swift
Labels: integration

#828 Documentation: Update CMake.md to use the ABI entry point
  Documentation/CMake.md
Labels: bug, documentation, tools integration, build

#1117 [CMake] Fix usage of lowercase or in condition
  Sources/CMakeLists.txt
Labels: bug, linux, build, freebsd

#1116 Include total number of suites in "run ended" console message
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Tests/TestingTests/EventRecorderTests.swift
Labels: enhancement, command-line experience

#1124 Remove the 'triage-needed' label from New Issue templates
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  .github/ISSUE_TEMPLATE/02-change-request.yml
Labels: enhancement

#1129 Revert "Work around a macOS CI failure (#1100)"
  Tests/TestingTests/IssueTests.swift
Labels: enhancement, workaround, build, self-reviewed, issue-handling
