Repository swiftlang/swift-testing, pull requests merged in 2025-09, with the labels that each got.

#1297 Extend test/task cancellation support to test case evaluation.
  Sources/Testing/Issues/Issue+Recording.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Running/SkipInfo.swift
  Tests/TestingTests/TestCancellationTests.swift
  Tests/TestingTests/TestSupport/TestingAdditions.swift
Labels: enhancement, public-api, issue-handling, parameterized-testing

#1287 Define an experimental event stream version and use it to conditionalize relevant content
  Sources/Testing/ABI/ABI.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedEvent.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedIssue.swift
  Sources/Testing/ABI/Encoded/ABI.EncodedTest.swift
  Sources/Testing/ABI/EntryPoints/EntryPoint.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Tests/TestingTests/SwiftPMTests.swift
Labels: enhancement, tools integration

#1296 Add CMake directions for the WinSDK overlay
  Package.swift
  Sources/Overlays/CMakeLists.txt
  Sources/Overlays/_Testing_WinSDK/Attachments/AttachableImageFormat+CLSID.swift
  Sources/Overlays/_Testing_WinSDK/Attachments/IWICBitmapSource+AttachableAsIWICBitmapSource.swift
  Sources/Overlays/_Testing_WinSDK/Attachments/_AttachableImageWrapper+AttachableWrapper.swift
  Sources/Overlays/_Testing_WinSDK/CMakeLists.txt
  Sources/Overlays/_Testing_WinSDK/Support/Additions/IWICImagingFactoryAdditions.swift
  Sources/Testing/Attachments/Images/ImageAttachmentError.swift
  Sources/Testing/Testing.swiftcrossimport/WinSDK.swiftoverlay
Labels: windows, build, attachments/activities, cross-import-overlays, image-attachments

#1305 Add task names to structured tasks we create.
  Sources/Testing/CMakeLists.txt
  Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Running/Runner.Plan.swift
  Sources/Testing/Running/Runner.swift
  Sources/Testing/Support/Additions/TaskAdditions.swift
  Sources/Testing/Test+Discovery.swift
  Sources/Testing/Traits/TimeLimitTrait.swift
Labels: enhancement, concurrency, tools integration

#1318 OpenBSD needs execinfo as well.
  Sources/Testing/CMakeLists.txt
Labels: bug, build, openbsd

#1322 [CI] Add Amazon Linux 2 in PR testing
  .github/workflows/pull_request.yml
Labels: enhancement, build

#1323 Remove a workaround for varargs not compiling on WASI.
  Sources/Testing/Events/TimeValue.swift
Labels: bug, workaround, wasi/wasm

#1326 Add Amazon Linux 2 in PR testing (take 2)
  .github/workflows/pull_request.yml
  Sources/Testing/ExitTests/ExitTest.swift
  Sources/Testing/Support/FileHandle.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: enhancement, linux, build

#1329 Merge more of the image attachments codebase duplicated between Darwin and Windows.
  Sources/Overlays/_Testing_CoreGraphics/Attachments/AttachableAsCGImage.swift
  Sources/Overlays/_Testing_CoreGraphics/CMakeLists.txt
  Sources/Overlays/_Testing_WinSDK/Attachments/AttachableAsIWICBitmapSource.swift
  Sources/Overlays/_Testing_WinSDK/Attachments/Attachment+AttachableAsIWICBitmapSource.swift
  Sources/Overlays/_Testing_WinSDK/Attachments/UnsafeMutablePointer+AttachableAsIWICBitmapSource.swift
  Sources/Overlays/_Testing_WinSDK/CMakeLists.txt
  Sources/Testing/Attachments/Images/Attachment+_AttachableAsImage.swift
  Sources/Testing/Attachments/Images/_AttachableAsImage.swift
  Sources/Testing/Attachments/Images/_AttachableImageWrapper.swift
  Sources/Testing/CMakeLists.txt
Labels: windows, darwin, attachments/activities, cross-import-overlays, tech-debt, image-attachments

#1338 Use generics to declare suite types in macro expansions.
  Sources/Testing/Parameterization/TypeInfo.swift
  Sources/Testing/Test+Macro.swift
  Sources/TestingMacros/TestDeclarationMacro.swift
  Tests/TestingTests/MiscellaneousTests.swift
  Tests/TestingTests/SwiftPMTests.swift
  Tests/TestingTests/TypeInfoTests.swift
Labels: enhancement, embedded-swift, macros

#1344 Adopt `_CFErrorCopyCallStackReturnAddresses()`.
  Sources/Testing/SourceAttribution/Backtrace.swift
Labels: enhancement, darwin, issue-handling

#1345 Provide opt-out condition for `sys_signame[]`.
  Sources/Testing/ExitTests/ExitStatus.swift
  Tests/TestingTests/ExitTestTests.swift
Labels: darwin, embedded-swift, build, android, freebsd, openbsd
